// 24-25 season setup data: prior-season (23-24) final standings, pre-drop rosters, manual
// cap-hit overrides, roster stubs, post-drop keeper rosters, and actual draft picks.
// Split out of roster_tracker.html to keep the main file size down; loaded via <script src> before the app script.

// 2023-24 final standings — determines 24-25 draft order (rank 9 picks first)
const FINAL_STANDINGS_2324 = {
  'Dumb and Goalie To':  {rank:1, pts:1224},
  'Motor City Wings':    {rank:2, pts:1152},
  'Damage Inc.':         {rank:3, pts:1137},
  'Pernicious Puckers':  {rank:4, pts:1104},
  'Killer Whales':       {rank:5, pts:1065},
  'Bossy Posse':         {rank:6, pts:1064},
  'Silence of the Lamb': {rank:7, pts:1049},
  'Muller Time!':        {rank:8, pts:1037},
  'Blue Line Bangers':   {rank:9, pts:907},
};

// 23-24 final rosters — pre-drop starting state for 24-25 simulation. Keys = normName.toLowerCase().
const PREDROP_ROSTER_2425 = {
  // Damage Inc. (19 players)
  'nikita kucherov':'Damage Inc.','brayden point':'Damage Inc.','mikko rantanen':'Damage Inc.',
  'william nylander':'Damage Inc.','mark scheifele':'Damage Inc.','drake batherson':'Damage Inc.',
  'leo carlsson':'Damage Inc.','kirill marchenko':'Damage Inc.','luke evangelista':'Damage Inc.',
  'yegor chinakhov':'Damage Inc.','connor zary':'Damage Inc.','matt boldy':'Damage Inc.',
  'jakob chychrun':'Damage Inc.','kandre miller':'Damage Inc.','luke hughes':'Damage Inc.',
  'kaiden guhle':'Damage Inc.','mike matheson':'Damage Inc.','kris letang':'Damage Inc.',
  'alexandar georgiev':'Damage Inc.','joey daccord':'Damage Inc.',
  // Blue Line Bangers (20 players)
  'adam fantilli':'Blue Line Bangers','adrian kempe':'Blue Line Bangers','alex tuch':'Blue Line Bangers',
  'brady skjei':'Blue Line Bangers','brayden mcnabb':'Blue Line Bangers','brock boeser':'Blue Line Bangers',
  'chandler stephenson':'Blue Line Bangers','connor hellebuyck':'Blue Line Bangers','connor ingram':'Blue Line Bangers',
  'eeli tolvanen':'Blue Line Bangers','elias lindholm':'Blue Line Bangers','jake middleton':'Blue Line Bangers',
  'jake neighbours':'Blue Line Bangers','jared mccann':'Blue Line Bangers','jordan spence':'Blue Line Bangers',
  'mason marchment':'Blue Line Bangers','noah hanifin':'Blue Line Bangers','trevor moore':'Blue Line Bangers',
  'tyler toffoli':'Blue Line Bangers','will borgen':'Blue Line Bangers',
  // Bossy Posse (20 players)
  'tage thompson':'Bossy Posse','ryan nugenthopkins':'Bossy Posse','kyle connor':'Bossy Posse',
  'zach hyman':'Bossy Posse','martin necas':'Bossy Posse','mason mctavish':'Bossy Posse',
  'nathan mackinnon':'Bossy Posse','pavel zacha':'Bossy Posse','juraj slafkovsky':'Bossy Posse',
  'morgan geekie':'Bossy Posse','trevor zegras':'Bossy Posse','joe pavelski':'Bossy Posse',
  'evan bouchard':'Bossy Posse','vince dunn':'Bossy Posse','david jiricek':'Bossy Posse',
  'rasmus sandin':'Bossy Posse','cam york':'Bossy Posse','simon nemec':'Bossy Posse',
  'juuse saros':'Bossy Posse','samuel ersson':'Bossy Posse',
  // Dumb and Goalie To (18 players)
  'brandon hagel':'Dumb and Goalie To','auston matthews':'Dumb and Goalie To','mats zuccarello':'Dumb and Goalie To',
  'pavel buchnevich':'Dumb and Goalie To','casey mittelstadt':'Dumb and Goalie To','jj peterka':'Dumb and Goalie To',
  'daniel sprong':'Dumb and Goalie To','david pastrnak':'Dumb and Goalie To','jonathan drouin':'Dumb and Goalie To',
  'artemi panarin':'Dumb and Goalie To','jack quinn':'Dumb and Goalie To','cale makar':'Dumb and Goalie To',
  'thomas harley':'Dumb and Goalie To','travis sanheim':'Dumb and Goalie To','mike reilly':'Dumb and Goalie To',
  'bowen byram':'Dumb and Goalie To','henry thrun':'Dumb and Goalie To','stuart skinner':'Dumb and Goalie To',
  'ukkopekka luukkonen':'Dumb and Goalie To','thomas novak':'Dumb and Goalie To',
  // Killer Whales (20 players)
  'jack hughes':'Killer Whales','andrei svechnikov':'Killer Whales','seth jarvis':'Killer Whales',
  'quinton byfield':'Killer Whales','william eklund':'Killer Whales','connor bedard':'Killer Whales',
  'owen tippett':'Killer Whales','cole perfetti':'Killer Whales','frank vatrano':'Killer Whales',
  'sebastian aho_F':'Killer Whales', // position-qualified: only the CAR forward, not SEA defenceman
  'joel farabee':'Killer Whales','nikolaj ehlers':'Killer Whales',
  'filip hronek':'Killer Whales','jamie drysdale':'Killer Whales','timothy liljegren':'Killer Whales',
  'josh morrissey':'Killer Whales','victor hedman':'Killer Whales','adam fox':'Killer Whales',
  'thatcher demko':'Killer Whales','cam talbot':'Killer Whales',
  // Motor City Wings (20 players)
  'kirill kaprizov':'Motor City Wings','sidney crosby':'Motor City Wings','evgeni malkin':'Motor City Wings',
  'jake guentzel':'Motor City Wings','dylan larkin':'Motor City Wings','lucas raymond':'Motor City Wings',
  'wyatt johnston':'Motor City Wings','clayton keller':'Motor City Wings','marco rossi':'Motor City Wings',
  'yegor sharangovich':'Motor City Wings','gustav nyquist':'Motor City Wings','dylan guenther':'Motor City Wings',
  'morgan rielly':'Motor City Wings','brandon montour':'Motor City Wings','shayne gostisbehere':'Motor City Wings',
  'jj moser':'Motor City Wings','egor zamula':'Motor City Wings','brandt clarke':'Motor City Wings',
  'jake oettinger':'Motor City Wings','alex lyon':'Motor City Wings',
  // Muller Time! (20 players — elias pettersson_F qualifies the F to avoid collision with D)
  'elias pettersson_F':'Muller Time!',
  'jonathan marchessault':'Muller Time!','cole caufield':'Muller Time!',
  'matias maccelli':'Muller Time!','logan cooley':'Muller Time!','matthew tkachuk':'Muller Time!',
  'carter verhaeghe':'Muller Time!','travis konecny':'Muller Time!','matthew poitras':'Muller Time!',
  'mitch marner':'Muller Time!','vincent trocheck':'Muller Time!','shane pinto':'Muller Time!',
  'noah dobson':'Muller Time!','devon toews':'Muller Time!','pavel mintyukov':'Muller Time!',
  'justin barron':'Muller Time!','kevin shattenkirk':'Muller Time!','calen addison':'Muller Time!',
  'pyotr kochetkov':'Muller Time!','igor shesterkin':'Muller Time!',
  // Pernicious Puckers (20 players)
  'leon draisaitl':'Pernicious Puckers','jason robertson':'Pernicious Puckers','jt miller':'Pernicious Puckers',
  'alex debrincat':'Pernicious Puckers','alexis lafreniere':'Pernicious Puckers','mika zibanejad':'Pernicious Puckers',
  'zach benson':'Pernicious Puckers','sam reinhart':'Pernicious Puckers','robert thomas':'Pernicious Puckers',
  'gabriel vilardi':'Pernicious Puckers','dmitri voronkov':'Pernicious Puckers','logan stankoven':'Pernicious Puckers',
  'quinn hughes':'Pernicious Puckers','sean durzi':'Pernicious Puckers','kevin korchinski':'Pernicious Puckers',
  'brock faber':'Pernicious Puckers','jake sanderson':'Pernicious Puckers','scott perunovich':'Pernicious Puckers',
  'ilya sorokin':'Pernicious Puckers','logan thompson':'Pernicious Puckers',
  // Silence of the Lamb (20 players)
  'connor mcdavid':'Silence of the Lamb','brad marchand':'Silence of the Lamb','brock nelson':'Silence of the Lamb',
  'jesper bratt':'Silence of the Lamb','matty beniers':'Silence of the Lamb','matthew knies':'Silence of the Lamb',
  'tim stutzle':'Silence of the Lamb','matt duchene':'Silence of the Lamb','patrick kane':'Silence of the Lamb',
  'ryan oreilly':'Silence of the Lamb','filip forsberg':'Silence of the Lamb','james van riemsdyk':'Silence of the Lamb',
  'moritz seider':'Silence of the Lamb','erik gustafsson':'Silence of the Lamb','rasmus andersson':'Silence of the Lamb',
  'gustav forsling':'Silence of the Lamb','darren raddysh':'Silence of the Lamb','braden schneider':'Silence of the Lamb',
  'linus ullmark':'Silence of the Lamb','jeremy swayman':'Silence of the Lamb',
};

// NHL.com 2024-25 forward/defenseman/goalie point projections — baked from the source CSV
// (2024-25 NHL_Proj.csv) so the 'NHL 24-25' button doesn't need a manual file upload.
// Keys = normName.toLowerCase()_posGroup.
const NHL_PROJ_2425 = {
  'aaron ekblad_D': {name:'Aaron Ekblad', pg:'D', hghl_pts:42},
  'adam fantilli_F': {name:'Adam Fantilli', pg:'F', hghl_pts:49},
  'adam fox_D': {name:'Adam Fox', pg:'D', hghl_pts:72},
  'adrian kempe_F': {name:'Adrian Kempe', pg:'F', hghl_pts:76},
  'aleksander barkov_F': {name:'Aleksander Barkov', pg:'F', hghl_pts:86},
  'alex debrincat_F': {name:'Alex DeBrincat', pg:'F', hghl_pts:73},
  'alex iafallo_F': {name:'Alex Iafallo', pg:'F', hghl_pts:45},
  'alex killorn_F': {name:'Alex Killorn', pg:'F', hghl_pts:40},
  'alex ovechkin_F': {name:'Alex Ovechkin', pg:'F', hghl_pts:70},
  'alex pietrangelo_D': {name:'Alex Pietrangelo', pg:'D', hghl_pts:51},
  'alex tuch_F': {name:'Alex Tuch', pg:'F', hghl_pts:69},
  'alexis lafreniere_F': {name:'Alexis Lafrenière', pg:'F', hghl_pts:70},
  'anders lee_F': {name:'Anders Lee', pg:'F', hghl_pts:40},
  'andrei kuzmenko_F': {name:'Andrei Kuzmenko', pg:'F', hghl_pts:56},
  'andrei svechnikov_F': {name:'Andrei Svechnikov', pg:'F', hghl_pts:72},
  'andrew mangiapane_F': {name:'Andrew Mangiapane', pg:'F', hghl_pts:43},
  'anthony cirelli_F': {name:'Anthony Cirelli', pg:'F', hghl_pts:55},
  'anthony duclair_F': {name:'Anthony Duclair', pg:'F', hghl_pts:59},
  'anton lundell_F': {name:'Anton Lundell', pg:'F', hghl_pts:45},
  'anze kopitar_F': {name:'Anze Kopitar', pg:'F', hghl_pts:70},
  'auston matthews_F': {name:'Auston Matthews', pg:'F', hghl_pts:110},
  'blake coleman_F': {name:'Blake Coleman', pg:'F', hghl_pts:64},
  'bo horvat_F': {name:'Bo Horvat', pg:'F', hghl_pts:74},
  'boone jenner_F': {name:'Boone Jenner', pg:'F', hghl_pts:55},
  'bowen byram_D': {name:'Bowen Byram', pg:'D', hghl_pts:49},
  'brad marchand_F': {name:'Brad Marchand', pg:'F', hghl_pts:66},
  'brady skjei_D': {name:'Brady Skjei', pg:'D', hghl_pts:46},
  'brady tkachuk_F': {name:'Brady Tkachuk', pg:'F', hghl_pts:81},
  'brandon hagel_F': {name:'Brandon Hagel', pg:'F', hghl_pts:73},
  'brandon montour_D': {name:'Brandon Montour', pg:'D', hghl_pts:62},
  'brandt clarke_D': {name:'Brandt Clarke', pg:'D', hghl_pts:42},
  'brayden point_F': {name:'Brayden Point', pg:'F', hghl_pts:105},
  'brayden schenn_F': {name:'Brayden Schenn', pg:'F', hghl_pts:48},
  'brent burns_D': {name:'Brent Burns', pg:'D', hghl_pts:45},
  'brock boeser_F': {name:'Brock Boeser', pg:'F', hghl_pts:68},
  'brock faber_D': {name:'Brock Faber', pg:'D', hghl_pts:56},
  'brock nelson_F': {name:'Brock Nelson', pg:'F', hghl_pts:71},
  'bryan rust_F': {name:'Bryan Rust', pg:'F', hghl_pts:60},
  'cale makar_D': {name:'Cale Makar', pg:'D', hghl_pts:95},
  'cam fowler_D': {name:'Cam Fowler', pg:'D', hghl_pts:31},
  'carter verhaeghe_F': {name:'Carter Verhaeghe', pg:'F', hghl_pts:79},
  'casey mittelstadt_F': {name:'Casey Mittelstadt', pg:'F', hghl_pts:62},
  'chandler stephenson_F': {name:'Chandler Stephenson', pg:'F', hghl_pts:58},
  'charlie coyle_F': {name:'Charlie Coyle', pg:'F', hghl_pts:55},
  'charlie mcavoy_D': {name:'Charlie McAvoy', pg:'D', hghl_pts:56},
  'chris kreider_F': {name:'Chris Kreider', pg:'F', hghl_pts:71},
  'claude giroux_F': {name:'Claude Giroux', pg:'F', hghl_pts:63},
  'clayton keller_F': {name:'Clayton Keller', pg:'F', hghl_pts:80},
  'cole caufield_F': {name:'Cole Caufield', pg:'F', hghl_pts:75},
  'cole perfetti_F': {name:'Cole Perfetti', pg:'F', hghl_pts:55},
  'connor bedard_F': {name:'Connor Bedard', pg:'F', hghl_pts:85},
  'connor mcdavid_F': {name:'Connor McDavid', pg:'F', hghl_pts:140},
  'cutter gauthier_F': {name:'Cutter Gauthier', pg:'F', hghl_pts:46},
  'david pastrnak_F': {name:'David Pastrnak', pg:'F', hghl_pts:107},
  'dawson mercer_F': {name:'Dawson Mercer', pg:'F', hghl_pts:48},
  'devon toews_D': {name:'Devon Toews', pg:'D', hghl_pts:54},
  'dmitri voronkov_F': {name:'Dmitri Voronkov', pg:'F', hghl_pts:45},
  'dmitry orlov_D': {name:'Dmitry Orlov', pg:'D', hghl_pts:33},
  'dougie hamilton_D': {name:'Dougie Hamilton', pg:'D', hghl_pts:67},
  'drake batherson_F': {name:'Drake Batherson', pg:'F', hghl_pts:68},
  'dylan cozens_F': {name:'Dylan Cozens', pg:'F', hghl_pts:60},
  'dylan guenther_F': {name:'Dylan Guenther', pg:'F', hghl_pts:52},
  'dylan holloway_F': {name:'Dylan Holloway', pg:'F', hghl_pts:45},
  'dylan larkin_F': {name:'Dylan Larkin', pg:'F', hghl_pts:80},
  'dylan strome_F': {name:'Dylan Strome', pg:'F', hghl_pts:66},
  'eeli tolvanen_F': {name:'Eeli Tolvanen', pg:'F', hghl_pts:53},
  'elias pettersson_F': {name:'Elias Pettersson', pg:'F', hghl_pts:86},
  'evan bouchard_D': {name:'Evan Bouchard', pg:'D', hghl_pts:90},
  'evgeni malkin_F': {name:'Evgeni Malkin', pg:'F', hghl_pts:70},
  'fabian zetterlund_F': {name:'Fabian Zetterlund', pg:'F', hghl_pts:47},
  'filip forsberg_F': {name:'Filip Forsberg', pg:'F', hghl_pts:86},
  'filip hronek_D': {name:'Filip Hronek', pg:'D', hghl_pts:46},
  'frank vatrano_F': {name:'Frank Vatrano', pg:'F', hghl_pts:62},
  'gabriel vilardi_F': {name:'Gabriel Vilardi', pg:'F', hghl_pts:62},
  'gustav forsling_D': {name:'Gustav Forsling', pg:'D', hghl_pts:49},
  'gustav nyquist_F': {name:'Gustav Nyquist', pg:'F', hghl_pts:54},
  'hampus lindholm_D': {name:'Hampus Lindholm', pg:'D', hghl_pts:39},
  'ivan barbashev_F': {name:'Ivan Barbashev', pg:'F', hghl_pts:56},
  'jack eichel_F': {name:'Jack Eichel', pg:'F', hghl_pts:84},
  'jack hughes_F': {name:'Jack Hughes', pg:'F', hghl_pts:103},
  'jack quinn_F': {name:'Jack Quinn', pg:'F', hghl_pts:48},
  'jake debrusk_F': {name:'Jake DeBrusk', pg:'F', hghl_pts:54},
  'jake guentzel_F': {name:'Jake Guentzel', pg:'F', hghl_pts:93},
  'jake neighbours_F': {name:'Jake Neighbours', pg:'F', hghl_pts:55},
  'jake sanderson_D': {name:'Jake Sanderson', pg:'D', hghl_pts:46},
  'jake walman_D': {name:'Jake Walman', pg:'D', hghl_pts:45},
  'jakob chychrun_D': {name:'Jakob Chychrun', pg:'D', hghl_pts:45},
  'jamie benn_F': {name:'Jamie Benn', pg:'F', hghl_pts:59},
  'jamie drysdale_D': {name:'Jamie Drysdale', pg:'D', hghl_pts:39},
  'jared mccann_F': {name:'Jared McCann', pg:'F', hghl_pts:70},
  'jared spurgeon_D': {name:'Jared Spurgeon', pg:'D', hghl_pts:34},
  'jeff skinner_F': {name:'Jeff Skinner', pg:'F', hghl_pts:74},
  'jesper bratt_F': {name:'Jesper Bratt', pg:'F', hghl_pts:85},
  'jj moser_D': {name:'J.J. Moser', pg:'D', hghl_pts:40},
  'jj peterka_F': {name:'JJ Peterka', pg:'F', hghl_pts:68},
  'joel farabee_F': {name:'Joel Farabee', pg:'F', hghl_pts:56},
  'john carlson_D': {name:'John Carlson', pg:'D', hghl_pts:54},
  'john tavares_F': {name:'John Tavares', pg:'F', hghl_pts:71},
  'jonas brodin_D': {name:'Jonas Brodin', pg:'D', hghl_pts:33},
  'jonathan drouin_F': {name:'Jonathan Drouin', pg:'F', hghl_pts:55},
  'jonathan huberdeau_F': {name:'Jonathan Huberdeau', pg:'F', hghl_pts:61},
  'jonathan marchessault_F': {name:'Jonathan Marchessault', pg:'F', hghl_pts:67},
  'jordan kyrou_F': {name:'Jordan Kyrou', pg:'F', hghl_pts:72},
  'jordan martinook_F': {name:'Jordan Martinook', pg:'F', hghl_pts:44},
  'josh doan_F': {name:'Josh Doan', pg:'F', hghl_pts:45},
  'josh manson_D': {name:'Josh Manson', pg:'D', hghl_pts:30},
  'josh morrissey_D': {name:'Josh Morrissey', pg:'D', hghl_pts:75},
  'josh norris_F': {name:'Josh Norris', pg:'F', hghl_pts:48},
  'jt compher_F': {name:'J.T. Compher', pg:'F', hghl_pts:52},
  'jt miller_F': {name:'J.T. Miller', pg:'F', hghl_pts:98},
  'juraj slafkovsky_F': {name:'Juraj Slafkovsky', pg:'F', hghl_pts:67},
  'justin faulk_D': {name:'Justin Faulk', pg:'D', hghl_pts:46},
  'kaapo kakko_F': {name:'Kaapo Kakko', pg:'F', hghl_pts:45},
  'kandre miller_D': {name:'K’Andre Miller', pg:'D', hghl_pts:46},
  'kevin fiala_F': {name:'Kevin Fiala', pg:'F', hghl_pts:77},
  'kevin hayes_F': {name:'Kevin Hayes', pg:'F', hghl_pts:44},
  'kevin korchinski_D': {name:'Kevin Korchinski', pg:'D', hghl_pts:30},
  'kirby dach_F': {name:'Kirby Dach', pg:'F', hghl_pts:40},
  'kirill kaprizov_F': {name:'Kirill Kaprizov', pg:'F', hghl_pts:104},
  'kirill marchenko_F': {name:'Kirill Marchenko', pg:'F', hghl_pts:47},
  'kris letang_D': {name:'Kris Letang', pg:'D', hghl_pts:55},
  'kyle connor_F': {name:'Kyle Connor', pg:'F', hghl_pts:80},
  'kyle palmieri_F': {name:'Kyle Palmieri', pg:'F', hghl_pts:51},
  'lane hutson_D': {name:'Lane Hutson', pg:'D', hghl_pts:38},
  'lawson crouse_F': {name:'Lawson Crouse', pg:'F', hghl_pts:48},
  'leo carlsson_F': {name:'Leo Carlsson', pg:'F', hghl_pts:45},
  'leon draisaitl_F': {name:'Leon Draisaitl', pg:'F', hghl_pts:120},
  'logan cooley_F': {name:'Logan Cooley', pg:'F', hghl_pts:61},
  'logan couture_F': {name:'Logan Couture', pg:'F', hghl_pts:50},
  'logan stankoven_F': {name:'Logan Stankoven', pg:'F', hghl_pts:61},
  'lucas raymond_F': {name:'Lucas Raymond', pg:'F', hghl_pts:72},
  'lukas reichel_F': {name:'Lukas Reichel', pg:'F', hghl_pts:45},
  'luke evangelista_F': {name:'Luke Evangelista', pg:'F', hghl_pts:48},
  'mackenzie weegar_D': {name:'MacKenzie Weegar', pg:'D', hghl_pts:55},
  'macklin celebrini_F': {name:'Macklin Celebrini', pg:'F', hghl_pts:60},
  'marat khusnutdinov_F': {name:'Marat Khusnutdinov', pg:'F', hghl_pts:44},
  'marco rossi_F': {name:'Marco Rossi', pg:'F', hghl_pts:53},
  'mark scheifele_F': {name:'Mark Scheifele', pg:'F', hghl_pts:85},
  'mark stone_F': {name:'Mark Stone', pg:'F', hghl_pts:64},
  'martin necas_F': {name:'Martin Necas', pg:'F', hghl_pts:60},
  'mason mctavish_F': {name:'Mason McTavish', pg:'F', hghl_pts:56},
  'mathew barzal_F': {name:'Mathew Barzal', pg:'F', hghl_pts:84},
  'mats zuccarello_F': {name:'Mats Zuccarello', pg:'F', hghl_pts:72},
  'matt duchene_F': {name:'Matt Duchene', pg:'F', hghl_pts:62},
  'matthew knies_F': {name:'Matthew Knies', pg:'F', hghl_pts:43},
  'matthew savoie_F': {name:'Matthew Savoie', pg:'F', hghl_pts:41},
  'matthew tkachuk_F': {name:'Matthew Tkachuk', pg:'F', hghl_pts:95},
  'mattias ekholm_D': {name:'Mattias Ekholm', pg:'D', hghl_pts:49},
  'mattias maccelli_F': {name:'Mattias Maccelli', pg:'F', hghl_pts:58},
  'matty beniers_F': {name:'Matty Beniers', pg:'F', hghl_pts:54},
  'matvei michkov_F': {name:'Matvei Michkov', pg:'F', hghl_pts:59},
  'mavrik bourque_F': {name:'Mavrik Bourque', pg:'F', hghl_pts:42},
  'max domi_F': {name:'Max Domi', pg:'F', hghl_pts:50},
  'maxim tsyplakov_F': {name:'Maxim Tsyplakov', pg:'F', hghl_pts:48},
  'michael bunting_F': {name:'Michael Bunting', pg:'F', hghl_pts:53},
  'mika zibanejad_F': {name:'Mika Zibanejad', pg:'F', hghl_pts:81},
  'mikael granlund_F': {name:'Mikael Granlund', pg:'F', hghl_pts:55},
  'mike matheson_D': {name:'Mike Matheson', pg:'D', hghl_pts:54},
  'mike reilly_D': {name:'Mike Reilly', pg:'D', hghl_pts:35},
  'mikhail sergachev_D': {name:'Mikhail Sergachev', pg:'D', hghl_pts:63},
  'mikko rantanen_F': {name:'Mikko Rantanen', pg:'F', hghl_pts:107},
  'miro heiskanen_D': {name:'Miro Heiskanen', pg:'D', hghl_pts:60},
  'mitch marner_F': {name:'Mitch Marner', pg:'F', hghl_pts:95},
  'morgan rielly_D': {name:'Morgan Rielly', pg:'D', hghl_pts:67},
  'moritz seider_D': {name:'Moritz Seider', pg:'D', hghl_pts:50},
  'nathan mackinnon_F': {name:'Nathan MacKinnon', pg:'F', hghl_pts:135},
  'nazem kadri_F': {name:'Nazem Kadri', pg:'F', hghl_pts:72},
  'neal pionk_D': {name:'Neal Pionk', pg:'D', hghl_pts:43},
  'nicholas paul_F': {name:'Nicholas Paul', pg:'F', hghl_pts:50},
  'nick schmaltz_F': {name:'Nick Schmaltz', pg:'F', hghl_pts:59},
  'nick suzuki_F': {name:'Nick Suzuki', pg:'F', hghl_pts:81},
  'nico hischier_F': {name:'Nico Hischier', pg:'F', hghl_pts:76},
  'nikita kucherov_F': {name:'Nikita Kucherov', pg:'F', hghl_pts:125},
  'nikolaj ehlers_F': {name:'Nikolaj Ehlers', pg:'F', hghl_pts:70},
  'noah dobson_D': {name:'Noah Dobson', pg:'D', hghl_pts:77},
  'noah hanifin_D': {name:'Noah Hanifin', pg:'D', hghl_pts:50},
  'olen zellweger_D': {name:'Olen Zellweger', pg:'D', hghl_pts:32},
  'oliver bjorkstrand_F': {name:'Oliver Bjorkstrand', pg:'F', hghl_pts:61},
  'oliver ekmanlarsson_D': {name:'Oliver Ekman-Larsson', pg:'D', hghl_pts:38},
  'owen power_D': {name:'Owen Power', pg:'D', hghl_pts:43},
  'owen tippett_F': {name:'Owen Tippett', pg:'F', hghl_pts:60},
  'patrick kane_F': {name:'Patrick Kane', pg:'F', hghl_pts:68},
  'pavel buchnevich_F': {name:'Pavel Buchnevich', pg:'F', hghl_pts:75},
  'pavel dorofeyev_F': {name:'Pavel Dorofeyev', pg:'F', hghl_pts:48},
  'pavel mintyukov_D': {name:'Pavel Mintyukov', pg:'D', hghl_pts:40},
  'pavel zacha_F': {name:'Pavel Zacha', pg:'F', hghl_pts:51},
  'philip broberg_D': {name:'Philip Broberg', pg:'D', hghl_pts:36},
  'philipp kurashev_F': {name:'Philipp Kurashev', pg:'F', hghl_pts:57},
  'phillip danault_F': {name:'Phillip Danault', pg:'F', hghl_pts:45},
  'pierreluc dubois_F': {name:'Pierre-Luc Dubois', pg:'F', hghl_pts:45},
  'quinn hughes_D': {name:'Quinn Hughes', pg:'D', hghl_pts:89},
  'quinton byfield_F': {name:'Quinton Byfield', pg:'F', hghl_pts:60},
  'rasmus andersson_D': {name:'Rasmus Andersson', pg:'D', hghl_pts:42},
  'rasmus dahlin_D': {name:'Rasmus Dahlin', pg:'D', hghl_pts:75},
  'rickard rakell_F': {name:'Rickard Rakell', pg:'F', hghl_pts:50},
  'robert thomas_F': {name:'Robert Thomas', pg:'F', hghl_pts:85},
  'roman josi_D': {name:'Roman Josi', pg:'D', hghl_pts:82},
  'roope hintz_F': {name:'Roope Hintz', pg:'F', hghl_pts:70},
  'rutger mcgroarty_F': {name:'Rutger McGroarty', pg:'F', hghl_pts:40},
  'ryan hartman_F': {name:'Ryan Hartman', pg:'F', hghl_pts:52},
  'ryan nugenthopkins_F': {name:'Ryan Nugent-Hopkins', pg:'F', hghl_pts:79},
  'ryan oreilly_F': {name:"Ryan O'Reilly", pg:'F', hghl_pts:66},
  'ryan pulock_D': {name:'Ryan Pulock', pg:'D', hghl_pts:30},
  'sam bennett_F': {name:'Sam Bennett', pg:'F', hghl_pts:51},
  'sam girard_D': {name:'Sam Girard', pg:'D', hghl_pts:33},
  'sam reinhart_F': {name:'Sam Reinhart', pg:'F', hghl_pts:85},
  'scott perunovich_D': {name:'Scott Perunovich', pg:'D', hghl_pts:38},
  'sean durzi_D': {name:'Sean Durzi', pg:'D', hghl_pts:44},
  'sean monahan_F': {name:'Sean Monahan', pg:'F', hghl_pts:58},
  'sean walker_D': {name:'Sean Walker', pg:'D', hghl_pts:30},
  'sebastian aho_F': {name:'Sebastian Aho', pg:'F', hghl_pts:90},
  'seth jarvis_F': {name:'Seth Jarvis', pg:'F', hghl_pts:69},
  'seth jones_D': {name:'Seth Jones', pg:'D', hghl_pts:50},
  'shane pinto_F': {name:'Shane Pinto', pg:'F', hghl_pts:50},
  'shane wright_F': {name:'Shane Wright', pg:'F', hghl_pts:48},
  'shayne gostisbehere_D': {name:'Shayne Gostisbehere', pg:'D', hghl_pts:48},
  'shea theodore_D': {name:'Shea Theodore', pg:'D', hghl_pts:54},
  'sidney crosby_F': {name:'Sidney Crosby', pg:'F', hghl_pts:97},
  'simon edvinsson_D': {name:'Simon Edvinsson', pg:'D', hghl_pts:30},
  'simon nemec_D': {name:'Simon Nemec', pg:'D', hghl_pts:40},
  'steven stamkos_F': {name:'Steven Stamkos', pg:'F', hghl_pts:79},
  'tage thompson_F': {name:'Tage Thompson', pg:'F', hghl_pts:82},
  'taylor hall_F': {name:'Taylor Hall', pg:'F', hghl_pts:48},
  'teuvo teravainen_F': {name:'Teuvo Teravainen', pg:'F', hghl_pts:62},
  'thomas chabot_D': {name:'Thomas Chabot', pg:'D', hghl_pts:49},
  'thomas harley_D': {name:'Thomas Harley', pg:'D', hghl_pts:49},
  'tim stutzle_F': {name:'Tim Stützle', pg:'F', hghl_pts:78},
  'timo meier_F': {name:'Timo Meier', pg:'F', hghl_pts:65},
  'tom wilson_F': {name:'Tom Wilson', pg:'F', hghl_pts:44},
  'tomas hertl_F': {name:'Tomas Hertl', pg:'F', hghl_pts:67},
  'tommy novak_F': {name:'Tommy Novak', pg:'F', hghl_pts:49},
  'travis konecny_F': {name:'Travis Konecny', pg:'F', hghl_pts:75},
  'travis sanheim_D': {name:'Travis Sanheim', pg:'D', hghl_pts:47},
  'trevor moore_F': {name:'Trevor Moore', pg:'F', hghl_pts:61},
  'trevor zegras_F': {name:'Trevor Zegras', pg:'F', hghl_pts:55},
  'troy terry_F': {name:'Troy Terry', pg:'F', hghl_pts:59},
  'tyler bertuzzi_F': {name:'Tyler Bertuzzi', pg:'F', hghl_pts:56},
  'tyler seguin_F': {name:'Tyler Seguin', pg:'F', hghl_pts:56},
  'tyler toffoli_F': {name:'Tyler Toffoli', pg:'F', hghl_pts:62},
  'tyson foerster_F': {name:'Tyson Foerster', pg:'F', hghl_pts:45},
  'victor hedman_D': {name:'Victor Hedman', pg:'D', hghl_pts:79},
  'victor olofsson_F': {name:'Victor Olofsson', pg:'F', hghl_pts:46},
  'viktor arvidsson_F': {name:'Viktor Arvidsson', pg:'F', hghl_pts:56},
  'vince dunn_D': {name:'Vince Dunn', pg:'D', hghl_pts:60},
  'vincent trocheck_F': {name:'Vincent Trocheck', pg:'F', hghl_pts:74},
  'vladimir tarasenko_F': {name:'Vladimir Tarasenko', pg:'F', hghl_pts:55},
  'will smith_F': {name:'Will Smith', pg:'F', hghl_pts:59},
  'william eklund_F': {name:'William Eklund', pg:'F', hghl_pts:48},
  'william karlsson_F': {name:'William Karlsson', pg:'F', hghl_pts:61},
  'william nylander_F': {name:'William Nylander', pg:'F', hghl_pts:100},
  'wyatt johnston_F': {name:'Wyatt Johnston', pg:'F', hghl_pts:75},
  'yegor chinakhov_F': {name:'Yegor Chinakhov', pg:'F', hghl_pts:46},
  'yegor sharangovich_F': {name:'Yegor Sharangovich', pg:'F', hghl_pts:60},
  'zac jones_D': {name:'Zac Jones', pg:'D', hghl_pts:32},
  'zach benson_F': {name:'Zach Benson', pg:'F', hghl_pts:58},
  'zach hyman_F': {name:'Zach Hyman', pg:'F', hghl_pts:86},
  'zach werenski_D': {name:'Zach Werenski', pg:'D', hghl_pts:65},
  // Missing forwards/defensemen from the original CSV, plus goalies entirely
  // (the CSV never included them) — added 2026-07 from a fresh NHL.com projections pull.
  'erik karlsson_D': {name:'Erik Karlsson', pg:'D', hghl_pts:55},
  'luke hughes_D': {name:'Luke Hughes', pg:'D', hghl_pts:50},
  'artyom levshunov_D': {name:'Artyom Levshunov', pg:'D', hghl_pts:35},
  'artemi panarin_F': {name:'Artemi Panarin', pg:'F', hghl_pts:106},
  'jason robertson_F': {name:'Jason Robertson', pg:'F', hghl_pts:85},
  'matt boldy_F': {name:'Matt Boldy', pg:'F', hghl_pts:76},
  'artturi lehkonen_F': {name:'Artturi Lehkonen', pg:'F', hghl_pts:68},
  'joel eriksson ek_F': {name:'Joel Eriksson Ek', pg:'F', hghl_pts:68},
  'elias lindholm_F': {name:'Elias Lindholm', pg:'F', hghl_pts:62},
  'patrik laine_F': {name:'Patrik Laine', pg:'F', hghl_pts:53},
  'nick paul_F': {name:'Nick Paul', pg:'F', hghl_pts:50},
  'jake oettinger_G': {name:'Jake Oettinger', pg:'G', hghl_pts:87.4},
  'alexandar georgiev_G': {name:'Alexandar Georgiev', pg:'G', hghl_pts:87.4},
  'igor shesterkin_G': {name:'Igor Shesterkin', pg:'G', hghl_pts:85.1},
  'stuart skinner_G': {name:'Stuart Skinner', pg:'G', hghl_pts:82.8},
  'juuse saros_G': {name:'Juuse Saros', pg:'G', hghl_pts:82.8},
  'connor hellebuyck_G': {name:'Connor Hellebuyck', pg:'G', hghl_pts:80.5},
  'andrei vasilevskiy_G': {name:'Andrei Vasilevskiy', pg:'G', hghl_pts:80.5},
  'sergei bobrovsky_G': {name:'Sergei Bobrovsky', pg:'G', hghl_pts:78.2},
  'jeremy swayman_G': {name:'Jeremy Swayman', pg:'G', hghl_pts:75.9},
  'joseph woll_G': {name:'Joseph Woll', pg:'G', hghl_pts:75.9},
  'thatcher demko_G': {name:'Thatcher Demko', pg:'G', hghl_pts:73.6},
  'jacob markstrom_G': {name:'Jacob Markstrom', pg:'G', hghl_pts:71.3},
  'adin hill_G': {name:'Adin Hill', pg:'G', hghl_pts:69},
  'darcy kuemper_G': {name:'Darcy Kuemper', pg:'G', hghl_pts:66.7},
  'ukkopekka luukkonen_G': {name:'Ukko-Pekka Luukkonen', pg:'G', hghl_pts:64.4},
  'linus ullmark_G': {name:'Linus Ullmark', pg:'G', hghl_pts:62.1},
  'jordan binnington_G': {name:'Jordan Binnington', pg:'G', hghl_pts:62.1},
  'frederik andersen_G': {name:'Frederik Andersen', pg:'G', hghl_pts:57.5},
  'ilya sorokin_G': {name:'Ilya Sorokin', pg:'G', hghl_pts:55.2},
  'connor ingram_G': {name:'Connor Ingram', pg:'G', hghl_pts:55.2},
  'joey daccord_G': {name:'Joey Daccord', pg:'G', hghl_pts:52.9},
  'pyotr kochetkov_G': {name:'Pyotr Kochetkov', pg:'G', hghl_pts:52.9},
  'alex lyon_G': {name:'Alex Lyon', pg:'G', hghl_pts:50.6},
  'ivan fedotov_G': {name:'Ivan Fedotov', pg:'G', hghl_pts:48.3},
  'samuel ersson_G': {name:'Samuel Ersson', pg:'G', hghl_pts:48.3},
  'cam talbot_G': {name:'Cam Talbot', pg:'G', hghl_pts:24.15},
  'ville husso_G': {name:'Ville Husso', pg:'G', hghl_pts:24.15},
  'tristan jarry_G': {name:'Tristan Jarry', pg:'G', hghl_pts:46},
  'filip gustavsson_G': {name:'Filip Gustavsson', pg:'G', hghl_pts:46},
  'logan thompson_G': {name:'Logan Thompson', pg:'G', hghl_pts:46},
  'marcandre fleury_G': {name:'Marc-Andre Fleury', pg:'G', hghl_pts:23},
  'jesper wallstedt_G': {name:'Jesper Wallstedt', pg:'G', hghl_pts:23},
  'vitek vanecek_G': {name:'Vitek Vanecek', pg:'G', hghl_pts:41.4},
  'dustin wolf_G': {name:'Dustin Wolf', pg:'G', hghl_pts:41.4},
  'elvis merzlikins_G': {name:'Elvis Merzlikins', pg:'G', hghl_pts:39.1},
  'karel vejmelka_G': {name:'Karel Vejmelka', pg:'G', hghl_pts:39.1},
  'semyon varlamov_G': {name:'Semyon Varlamov', pg:'G', hghl_pts:36.8},
  'alex nedeljkovic_G': {name:'Alex Nedeljkovic', pg:'G', hghl_pts:36.8},
  'sam montembeault_G': {name:'Sam Montembeault', pg:'G', hghl_pts:36.8},
  'lukas dostal_G': {name:'Lukas Dostal', pg:'G', hghl_pts:34.5},
  'john gibson_G': {name:'John Gibson', pg:'G', hghl_pts:34.5},
  'james reimer_G': {name:'James Reimer', pg:'G', hghl_pts:17.25},
  'devon levi_G': {name:'Devon Levi', pg:'G', hghl_pts:17.25},
  'casey desmith_G': {name:'Casey DeSmith', pg:'G', hghl_pts:34.5},
  'calvin pickard_G': {name:'Calvin Pickard', pg:'G', hghl_pts:34.5},
  'cayden primeau_G': {name:'Cayden Primeau', pg:'G', hghl_pts:34.5},
  'jake allen_G': {name:'Jake Allen', pg:'G', hghl_pts:34.5},
  'philipp grubauer_G': {name:'Philipp Grubauer', pg:'G', hghl_pts:34.5},
  'charlie lindgren_G': {name:'Charlie Lindgren', pg:'G', hghl_pts:34.5},
  'spencer knight_G': {name:'Spencer Knight', pg:'G', hghl_pts:32.2},
  'laurent brossoit_G': {name:'Laurent Brossoit', pg:'G', hghl_pts:32.2},
  'petr mrazek_G': {name:'Petr Mrazek', pg:'G', hghl_pts:32.2},
  'jonathan quick_G': {name:'Jonathan Quick', pg:'G', hghl_pts:29.9},
  'scott wedgewood_G': {name:'Scott Wedgewood', pg:'G', hghl_pts:29.9},
  'david rittich_G': {name:'David Rittich', pg:'G', hghl_pts:29.9},
  'anton forsberg_G': {name:'Anton Forsberg', pg:'G', hghl_pts:29.9},
  'joel hofer_G': {name:'Joel Hofer', pg:'G', hghl_pts:29.9},
  'joonas korpisalo_G': {name:'Joonas Korpisalo', pg:'G', hghl_pts:29.9},
  'anthony stolarz_G': {name:'Anthony Stolarz', pg:'G', hghl_pts:13.8},
  'matt murray_G': {name:'Matt Murray', pg:'G', hghl_pts:13.8},
  'arturs silovs_G': {name:'Arturs Silovs', pg:'G', hghl_pts:25.3},
  'kaapo kahkonen_G': {name:'Kaapo Kahkonen', pg:'G', hghl_pts:12.65},
  'eric comrie_G': {name:'Eric Comrie', pg:'G', hghl_pts:12.65},
  'dan vladar_G': {name:'Dan Vladar', pg:'G', hghl_pts:23},
  'justus annunen_G': {name:'Justus Annunen', pg:'G', hghl_pts:23},
  'daniil tarasov_G': {name:'Daniil Tarasov', pg:'G', hghl_pts:23},
  'mackenzie blackwood_G': {name:'Mackenzie Blackwood', pg:'G', hghl_pts:11.5},
  'yaroslav askarov_G': {name:'Yaroslav Askarov', pg:'G', hghl_pts:11.5},
  'jonas johansson_G': {name:'Jonas Johansson', pg:'G', hghl_pts:18.4},
};

// Manual 2024-25 cap hits for players whose PuckPedia slugs 404 or had no page contract panel.
// Key = normName(name).toLowerCase() + "_" + posGroup. yrStr = contract year label.
const MANUAL_CAPS_2425 = {
  'cam york_D':       { cap: 1.6000, yrStr: 'Yr 2 / 2' },
  'matty beniers_F':  { cap: 7.1400, yrStr: 'Yr 1 / 7' },
  'will borgen_D':    { cap: 2.7000, yrStr: 'Yr 2 / 2' },
  'egor zamula_D':    { cap: 1.7000, yrStr: 'Yr 1 / 2' },
  'jake middleton_D': { cap: 2.4500, yrStr: 'Yr 3 / 3' },
  'nick perbix_D':    { cap: 1.1250, yrStr: 'Yr 2 / 2' },
  'jj moser_D':       { cap: 3.3750, yrStr: 'Yr 1 / 2' },
  'jj peterka_F':     { cap: 0.8558, yrStr: 'Yr 3 / 3' },
  'calen addison_D':  { cap: 0,      yrStr: '' },          // no 2024-25 contract
};

// Players that may not have a record in the main players array (retired, low-profile, etc.)
// Created as stubs during resetSim2425() if missing.
const PREDROP_STUBS_2425 = [
  {name:'Calen Addison',      pos:'D'},
  {name:'Kevin Shattenkirk',  pos:'D'},
  {name:'Alexandar Georgiev', pos:'G'},
  {name:'Yegor Chinakhov',    pos:'RW'},
  {name:'Matthew Poitras',   pos:'C'},
  {name:'Henry Thrun',       pos:'D'},
  {name:'Daniel Sprong',     pos:'RW'},
  {name:'Joe Pavelski',      pos:'C'},
  {name:'Cam Talbot',        pos:'G'},
  // Below: the remaining ~171 PREDROP_ROSTER_2425 players not covered above, filled in
  // 2026-08-19 (was previously only 9 entries, silently running Compare Drops 24-25 on a
  // fraction of the real ~180-player dataset). Positions cross-referenced from the same
  // players' entries in PREDROP_STUBS_2324/2526 where available; the rest filled in from
  // general knowledge. Verified complete (180/180 PREDROP_ROSTER_2425 entries resolve to
  // either an existing player or a stub here) 2026-09-15.
  {name:'Nikita Kucherov', pos:'F'},
  {name:'Brayden Point', pos:'F'},
  {name:'Mikko Rantanen', pos:'F'},
  {name:'William Nylander', pos:'F'},
  {name:'Mark Scheifele', pos:'F'},
  {name:'Drake Batherson', pos:'F'},
  {name:'Leo Carlsson', pos:'F'},
  {name:'Kirill Marchenko', pos:'F'},
  {name:'Luke Evangelista', pos:'F'},
  {name:'Connor Zary', pos:'F'},
  {name:'Matt Boldy', pos:'F'},
  {name:'Jakob Chychrun', pos:'D'},
  {name:"K'Andre Miller", pos:'D'},
  {name:'Luke Hughes', pos:'D'},
  {name:'Kaiden Guhle', pos:'D'},
  {name:'Mike Matheson', pos:'D'},
  {name:'Kris Letang', pos:'D'},
  {name:'Joey Daccord', pos:'G'},
  {name:'Adam Fantilli', pos:'F'},
  {name:'Adrian Kempe', pos:'F'},
  {name:'Alex Tuch', pos:'F'},
  {name:'Brady Skjei', pos:'D'},
  {name:'Brayden Mcnabb', pos:'D'},
  {name:'Brock Boeser', pos:'F'},
  {name:'Chandler Stephenson', pos:'F'},
  {name:'Connor Hellebuyck', pos:'G'},
  {name:'Connor Ingram', pos:'G'},
  {name:'Eeli Tolvanen', pos:'F'},
  {name:'Elias Lindholm', pos:'F'},
  {name:'Jake Middleton', pos:'D'},
  {name:'Jake Neighbours', pos:'F'},
  {name:'Jared McCann', pos:'F'},
  {name:'Jordan Spence', pos:'D'},
  {name:'Mason Marchment', pos:'F'},
  {name:'Noah Hanifin', pos:'D'},
  {name:'Trevor Moore', pos:'F'},
  {name:'Tyler Toffoli', pos:'F'},
  {name:'Will Borgen', pos:'D'},
  {name:'Tage Thompson', pos:'F'},
  {name:'Ryan Nugent-Hopkins', pos:'F'},
  {name:'Kyle Connor', pos:'F'},
  {name:'Zach Hyman', pos:'F'},
  {name:'Martin Necas', pos:'F'},
  {name:'Mason McTavish', pos:'F'},
  {name:'Nathan MacKinnon', pos:'F'},
  {name:'Pavel Zacha', pos:'F'},
  {name:'Juraj Slafkovsky', pos:'F'},
  {name:'Morgan Geekie', pos:'F'},
  {name:'Trevor Zegras', pos:'F'},
  {name:'Evan Bouchard', pos:'D'},
  {name:'Vince Dunn', pos:'D'},
  {name:'David Jiricek', pos:'D'},
  {name:'Rasmus Sandin', pos:'D'},
  {name:'Cam York', pos:'D'},
  {name:'Simon Nemec', pos:'D'},
  {name:'Juuse Saros', pos:'G'},
  {name:'Samuel Ersson', pos:'G'},
  {name:'Brandon Hagel', pos:'F'},
  {name:'Auston Matthews', pos:'F'},
  {name:'Mats Zuccarello', pos:'F'},
  {name:'Pavel Buchnevich', pos:'F'},
  {name:'Casey Mittelstadt', pos:'F'},
  {name:'JJ Peterka', pos:'F'},
  {name:'David Pastrnak', pos:'F'},
  {name:'Jonathan Drouin', pos:'F'},
  {name:'Artemi Panarin', pos:'F'},
  {name:'Jack Quinn', pos:'F'},
  {name:'Cale Makar', pos:'D'},
  {name:'Thomas Harley', pos:'D'},
  {name:'Travis Sanheim', pos:'D'},
  {name:'Mike Reilly', pos:'D'},
  {name:'Bowen Byram', pos:'D'},
  {name:'Stuart Skinner', pos:'G'},
  {name:'Ukko-Pekka Luukkonen', pos:'G'},
  {name:'Thomas Novak', pos:'F'},
  {name:'Jack Hughes', pos:'F'},
  {name:'Andrei Svechnikov', pos:'F'},
  {name:'Seth Jarvis', pos:'F'},
  {name:'Quinton Byfield', pos:'F'},
  {name:'William Eklund', pos:'F'},
  {name:'Connor Bedard', pos:'F'},
  {name:'Owen Tippett', pos:'F'},
  {name:'Cole Perfetti', pos:'F'},
  {name:'Frank Vatrano', pos:'F'},
  {name:'Sebastian Aho', pos:'F'},
  {name:'Joel Farabee', pos:'F'},
  {name:'Nikolaj Ehlers', pos:'F'},
  {name:'Filip Hronek', pos:'D'},
  {name:'Jamie Drysdale', pos:'D'},
  {name:'Timothy Liljegren', pos:'D'},
  {name:'Josh Morrissey', pos:'D'},
  {name:'Victor Hedman', pos:'D'},
  {name:'Adam Fox', pos:'D'},
  {name:'Thatcher Demko', pos:'G'},
  {name:'Kirill Kaprizov', pos:'F'},
  {name:'Sidney Crosby', pos:'F'},
  {name:'Evgeni Malkin', pos:'F'},
  {name:'Jake Guentzel', pos:'F'},
  {name:'Dylan Larkin', pos:'F'},
  {name:'Lucas Raymond', pos:'F'},
  {name:'Wyatt Johnston', pos:'F'},
  {name:'Clayton Keller', pos:'F'},
  {name:'Marco Rossi', pos:'F'},
  {name:'Yegor Sharangovich', pos:'F'},
  {name:'Gustav Nyquist', pos:'F'},
  {name:'Dylan Guenther', pos:'F'},
  {name:'Morgan Rielly', pos:'D'},
  {name:'Brandon Montour', pos:'D'},
  {name:'Shayne Gostisbehere', pos:'D'},
  {name:'J.J. Moser', pos:'D'},
  {name:'Egor Zamula', pos:'D'},
  {name:'Brandt Clarke', pos:'D'},
  {name:'Jake Oettinger', pos:'G'},
  {name:'Alex Lyon', pos:'G'},
  {name:'Elias Pettersson', pos:'F'},
  {name:'Jonathan Marchessault', pos:'F'},
  {name:'Cole Caufield', pos:'F'},
  {name:'Matias Maccelli', pos:'F'},
  {name:'Logan Cooley', pos:'F'},
  {name:'Matthew Tkachuk', pos:'F'},
  {name:'Carter Verhaeghe', pos:'F'},
  {name:'Travis Konecny', pos:'F'},
  {name:'Mitch Marner', pos:'F'},
  {name:'Vincent Trocheck', pos:'F'},
  {name:'Shane Pinto', pos:'F'},
  {name:'Noah Dobson', pos:'D'},
  {name:'Devon Toews', pos:'D'},
  {name:'Pavel Mintyukov', pos:'D'},
  {name:'Justin Barron', pos:'D'},
  {name:'Pyotr Kochetkov', pos:'G'},
  {name:'Igor Shesterkin', pos:'G'},
  {name:'Leon Draisaitl', pos:'F'},
  {name:'Jason Robertson', pos:'F'},
  {name:'J.T. Miller', pos:'F'},
  {name:'Alex DeBrincat', pos:'F'},
  {name:'Alexis Lafreniere', pos:'F'},
  {name:'Mika Zibanejad', pos:'F'},
  {name:'Zach Benson', pos:'F'},
  {name:'Sam Reinhart', pos:'F'},
  {name:'Robert Thomas', pos:'F'},
  {name:'Gabriel Vilardi', pos:'F'},
  {name:'Dmitri Voronkov', pos:'F'},
  {name:'Logan Stankoven', pos:'F'},
  {name:'Quinn Hughes', pos:'D'},
  {name:'Sean Durzi', pos:'D'},
  {name:'Kevin Korchinski', pos:'D'},
  {name:'Brock Faber', pos:'D'},
  {name:'Jake Sanderson', pos:'D'},
  {name:'Scott Perunovich', pos:'D'},
  {name:'Ilya Sorokin', pos:'G'},
  {name:'Logan Thompson', pos:'G'},
  {name:'Connor McDavid', pos:'F'},
  {name:'Brad Marchand', pos:'F'},
  {name:'Brock Nelson', pos:'F'},
  {name:'Jesper Bratt', pos:'F'},
  {name:'Matty Beniers', pos:'F'},
  {name:'Matthew Knies', pos:'F'},
  {name:'Tim Stutzle', pos:'F'},
  {name:'Matt Duchene', pos:'F'},
  {name:'Patrick Kane', pos:'F'},
  {name:"Ryan O'Reilly", pos:'F'},
  {name:'Filip Forsberg', pos:'F'},
  {name:'James van Riemsdyk', pos:'F'},
  {name:'Moritz Seider', pos:'D'},
  {name:'Erik Gustafsson', pos:'D'},
  {name:'Rasmus Andersson', pos:'D'},
  {name:'Gustav Forsling', pos:'D'},
  {name:'Darren Raddysh', pos:'D'},
  {name:'Braden Schneider', pos:'D'},
  {name:'Linus Ullmark', pos:'G'},
  {name:'Jeremy Swayman', pos:'G'},
];

// Post-drop pre-pick 24-25 rosters. Keys = normName.toLowerCase().
const POSTDROP_ROSTER_2425 = {
  // Damage Inc. (14 keepers — dropped: Nylander, Scheifele, Chinakhov, Chychrun, Letang)
  'nikita kucherov':'Damage Inc.','brayden point':'Damage Inc.','mikko rantanen':'Damage Inc.',
  'drake batherson':'Damage Inc.','leo carlsson':'Damage Inc.','kirill marchenko':'Damage Inc.',
  'luke evangelista':'Damage Inc.','connor zary':'Damage Inc.','matt boldy':'Damage Inc.',
  'kandre miller':'Damage Inc.','luke hughes':'Damage Inc.','kaiden guhle':'Damage Inc.',
  'mike matheson':'Damage Inc.','alexandar georgiev':'Damage Inc.','joey daccord':'Damage Inc.',
  // Blue Line Bangers (10 keepers — dropped: Skjei, McNabb, Stephenson, Tolvanen, Lindholm, Middleton, Marchment, Hanifin, Moore, Toffoli)
  'adam fantilli':'Blue Line Bangers','adrian kempe':'Blue Line Bangers','alex tuch':'Blue Line Bangers',
  'brock boeser':'Blue Line Bangers','connor hellebuyck':'Blue Line Bangers','connor ingram':'Blue Line Bangers',
  'jake neighbours':'Blue Line Bangers','jared mccann':'Blue Line Bangers','jordan spence':'Blue Line Bangers',
  'will borgen':'Blue Line Bangers',
  // Bossy Posse (15 keepers — dropped: Necas, Pavelski, Dunn, Sandin, Ersson)
  'tage thompson':'Bossy Posse','ryan nugenthopkins':'Bossy Posse','kyle connor':'Bossy Posse',
  'zach hyman':'Bossy Posse','mason mctavish':'Bossy Posse','nathan mackinnon':'Bossy Posse',
  'pavel zacha':'Bossy Posse','juraj slafkovsky':'Bossy Posse','morgan geekie':'Bossy Posse',
  'trevor zegras':'Bossy Posse','evan bouchard':'Bossy Posse','david jiricek':'Bossy Posse',
  'cam york':'Bossy Posse','simon nemec':'Bossy Posse','juuse saros':'Bossy Posse',
  // Dumb and Goalie To (13 keepers — dropped: Matthews, Mittelstadt, Sanheim, Reilly, Thrun)
  'brandon hagel':'Dumb and Goalie To','pavel buchnevich':'Dumb and Goalie To','jj peterka':'Dumb and Goalie To',
  'daniel sprong':'Dumb and Goalie To','david pastrnak':'Dumb and Goalie To','jonathan drouin':'Dumb and Goalie To',
  'artemi panarin':'Dumb and Goalie To','jack quinn':'Dumb and Goalie To','cale makar':'Dumb and Goalie To',
  'thomas harley':'Dumb and Goalie To','bowen byram':'Dumb and Goalie To','stuart skinner':'Dumb and Goalie To',
  'mats zuccarello':'Dumb and Goalie To',
  'ukkopekka luukkonen':'Dumb and Goalie To','thomas novak':'Dumb and Goalie To',
  // Killer Whales (12 keepers — dropped: Svechnikov, Aho, Ehlers, Hronek, Liljegren, Fox, Demko, Talbot)
  'jack hughes':'Killer Whales','seth jarvis':'Killer Whales','quinton byfield':'Killer Whales',
  'william eklund':'Killer Whales','connor bedard':'Killer Whales','owen tippett':'Killer Whales',
  'cole perfetti':'Killer Whales','frank vatrano':'Killer Whales','jamie drysdale':'Killer Whales',
  'josh morrissey':'Killer Whales','victor hedman':'Killer Whales','joel farabee':'Killer Whales',
  // Motor City Wings (14 keepers — dropped: Malkin, Sharangovich, Montour, Moser, Zamula, Lyon)
  'kirill kaprizov':'Motor City Wings','sidney crosby':'Motor City Wings','jake guentzel':'Motor City Wings',
  'dylan larkin':'Motor City Wings','lucas raymond':'Motor City Wings','wyatt johnston':'Motor City Wings',
  'clayton keller':'Motor City Wings','marco rossi':'Motor City Wings','gustav nyquist':'Motor City Wings',
  'dylan guenther':'Motor City Wings','morgan rielly':'Motor City Wings','shayne gostisbehere':'Motor City Wings',
  'brandt clarke':'Motor City Wings','jake oettinger':'Motor City Wings',
  // Muller Time! (14 keepers — dropped: Pettersson, Caufield, Toews, Barron, Shattenkirk, Addison)
  'jonathan marchessault':'Muller Time!','matias maccelli':'Muller Time!','logan cooley':'Muller Time!',
  'matthew tkachuk':'Muller Time!','carter verhaeghe':'Muller Time!','travis konecny':'Muller Time!',
  'matthew poitras':'Muller Time!','mitch marner':'Muller Time!','vincent trocheck':'Muller Time!',
  'shane pinto':'Muller Time!','noah dobson':'Muller Time!','pavel mintyukov':'Muller Time!',
  'pyotr kochetkov':'Muller Time!','igor shesterkin':'Muller Time!',
  // Pernicious Puckers (13 keepers — dropped: Zibanejad, Vilardi, Voronkov, Durzi, Sanderson, Sorokin, Thompson)
  'leon draisaitl':'Pernicious Puckers','jason robertson':'Pernicious Puckers','jt miller':'Pernicious Puckers',
  'alex debrincat':'Pernicious Puckers','alexis lafreniere':'Pernicious Puckers','zach benson':'Pernicious Puckers',
  'sam reinhart':'Pernicious Puckers','logan stankoven':'Pernicious Puckers','quinn hughes':'Pernicious Puckers',
  'kevin korchinski':'Pernicious Puckers','brock faber':'Pernicious Puckers','scott perunovich':'Pernicious Puckers',
  'robert thomas':'Pernicious Puckers',
  // Silence of the Lamb (13 keepers — dropped: Beniers, Stutzle, Seider, Forsling, Schneider, Ullmark, Swayman)
  'connor mcdavid':'Silence of the Lamb','brad marchand':'Silence of the Lamb','brock nelson':'Silence of the Lamb',
  'jesper bratt':'Silence of the Lamb','matthew knies':'Silence of the Lamb','matt duchene':'Silence of the Lamb',
  'patrick kane':'Silence of the Lamb','ryan oreilly':'Silence of the Lamb','filip forsberg':'Silence of the Lamb',
  'james van riemsdyk':'Silence of the Lamb','erik gustafsson':'Silence of the Lamb',
  'rasmus andersson':'Silence of the Lamb','darren raddysh':'Silence of the Lamb',
};

// Actual 24-25 draft picks. Keys = normName.toLowerCase(), values = team.
const POSTDRAFT_ROSTER_2425 = {
  // Blue Line Bangers (10 picks)
  'macklin celebrini':'Blue Line Bangers',
  'mackenzie weegar':'Blue Line Bangers',
  'nico hischier':'Blue Line Bangers',
  'gustav forsling':'Blue Line Bangers',
  'elias pettersson_F':'Blue Line Bangers',  // F (VAN) — disambiguates from Elias Pettersson D (SEA)
  'nick schmaltz':'Blue Line Bangers',
  'michael kesselring':'Blue Line Bangers',
  'juuso valimaki':'Blue Line Bangers',
  'rutger mcgroarty':'Blue Line Bangers',
  'dylan cozens':'Blue Line Bangers',
  // Muller Time! (6 picks)
  'matvei michkov':'Muller Time!',
  'shea theodore':'Muller Time!',
  'denton mateychuk':'Muller Time!',
  'auston matthews':'Muller Time!',
  'jj moser':'Muller Time!',
  'justin barron':'Muller Time!',
  // Silence of the Lamb (7 picks)
  'cutter gauthier':'Silence of the Lamb',
  'charlie lindgren':'Silence of the Lamb',
  'samuel ersson':'Silence of the Lamb',
  'roman josi':'Silence of the Lamb',
  'kris letang':'Silence of the Lamb',
  'joel eriksson ek':'Silence of the Lamb',
  'mike reilly':'Silence of the Lamb',
  // Bossy Posse (5 picks)
  'joseph woll':'Bossy Posse',
  'adam fox':'Bossy Posse',
  'william nylander':'Bossy Posse',
  'shane wright':'Bossy Posse',
  'nick perbix':'Bossy Posse',
  // Killer Whales (8 picks)
  'will smith':'Killer Whales',
  'jacob markstrom':'Killer Whales',
  'dustin wolf':'Killer Whales',
  'miro heiskanen':'Killer Whales',
  'braden schneider':'Killer Whales',
  'ty emberson':'Killer Whales',
  'nazem kadri':'Killer Whales',
  'fabian zetterlund':'Killer Whales',
  // Pernicious Puckers (7 picks)
  'lane hutson':'Pernicious Puckers',
  'simon edvinsson':'Pernicious Puckers',
  'tim stutzle':'Pernicious Puckers',
  'nick suzuki':'Pernicious Puckers',
  'arturs silovs':'Pernicious Puckers',
  'filip gustavsson':'Pernicious Puckers',
  'victor olofsson':'Pernicious Puckers',
  // Damage Inc. (5 picks)
  'adam boqvist':'Damage Inc.',
  'henry thrun':'Damage Inc.',
  'mathew barzal':'Damage Inc.',
  'jordan kyrou':'Damage Inc.',
  'dylan strome':'Damage Inc.',
  // Motor City Wings (6 picks)
  'olen zellweger':'Motor City Wings',
  'mason lohrei':'Motor City Wings',
  'ridly greig':'Motor City Wings',
  'jake walman':'Motor City Wings',
  'teuvo teravainen':'Motor City Wings',
  'alex lyon':'Motor City Wings',
  // Dumb and Goalie To (5 picks)
  'seamus casey':'Dumb and Goalie To',
  'jeff skinner':'Dumb and Goalie To',
  'josh doan':'Dumb and Goalie To',
  'jakob chychrun':'Dumb and Goalie To',
  'oliver ekmanlarsson':'Dumb and Goalie To',
};

// All in-season 'drop' transactions for 24-25, keyed by team, used to check whether a
// player the algo recommended dropping (but the manager initially kept) was later dropped
// anyway that season — a 'vindicated' call, not a pure miss. See compareDrops2425().
// Excludes any drop immediately reversed by a same-team re-add within 48h (mistake/trade-
// mechanic noise, not a genuine decision) — confirmed a real pattern in this data, not hypothetical.
const MIDSEASON_DROPS_2425 = {
  'Blue Line Bangers': ['bobby mcmann_F', 'brock boeser_F', 'connor ingram_G', 'dylan cozens_F', 'elias pettersson_F', 'juuso valimaki_D', 'ross colton_F', 'rutger mcgroarty_F', 'will borgen_D'],
  'Bossy Posse': ['adam fox_D', 'david jiricek_D', 'egor chinakhov_F', 'morgan geekie_F', 'nick perbix_D', 'simon nemec_D', 'trevor zegras_F', 'ty smith_D', 'william nylander_F'],
  'Damage Inc.': ['alexandar georgiev_G', 'connor zary_F', 'henry thrun_D', 'kaiden guhle_D', 'kandre miller_D', 'luke evangelista_F', 'mathew barzal_F', 'mike matheson_D'],
  'Dumb and Goalie To': ['daniel sprong_F', 'jack roslovic_F', 'jeff skinner_F', 'josh doan_F', 'mats zuccarello_F', 'paul cotter_F', 'pavel buchnevich_F', 'thomas novak_F', 'ukkopekka luukkonen_G'],
  'Killer Whales': ['anton lundell_F', 'braden schneider_D', 'emil andrae_D', 'joel farabee_F', 'miro heiskanen_D', 'nazem kadri_F', 'owen tippett_F', 'ty emberson_D'],
  'Motor City Wings': ['dylan guenther_F', 'gabriel vilardi_F', 'gustav nyquist_F', 'morgan rielly_D', 'ridly greig_F', 'teuvo teravainen_F'],
  'Muller Time!': ['auston matthews_F', 'jj moser_D', 'jonathan marchessault_F', 'justin barron_D', 'matias maccelli_F', 'matthew poitras_F', 'pavel dorofeyev_F', 'rickard rakell_F', 'shane pinto_F'],
  'Pernicious Puckers': ['alex vlasic_D', 'alexis lafreniere_F', 'arturs silovs_G', 'casey mittelstadt_F', 'declan chisholm_D', 'justus annunen_G', 'kevin korchinski_D', 'robert thomas_F', 'scott perunovich_D'],
  'Silence of the Lamb': ['brock nelson_F', 'evgeni malkin_F', 'filip forsberg_F', 'joel eriksson ek_F', 'kris letang_D', 'mike reilly_D', 'rasmus dahlin_D', 'roman josi_D', 'ryan oreilly_F', 'samuel ersson_G', 'taylor raddysh_F'],
};

// All in-season 'add' transactions for 24-25, keyed by team, used to check whether a
// player the algo recommended keeping (but the manager initially dropped) was re-acquired by
// that SAME team later that season — a 'vindicated' call for the keep side, mirroring
// MIDSEASON_DROPS_2425. See compareDrops2425().
// Excludes any add immediately reversed by a same-team drop within 48h (test-drive-and-cut
// noise / trade-mechanic artifact, not a genuine decision to bring the player back).
const MIDSEASON_READDS_2425 = {
  'Blue Line Bangers': ['alex laferriere_F', 'anthony cirelli_F', 'bobby mcmann_F', 'brandon montour_D', 'ivan demidov_F', 'jack eichel_F', 'kevin lankinen_G', 'neal pionk_D', 'ross colton_F'],
  'Bossy Posse': ['adam fox_D', 'egor chinakhov_F', 'jackson lacombe_D', 'kaapo kakko_F', 'matt coronato_F', 'robert thomas_F', 'ryker evans_D', 'ty smith_D', 'vince dunn_D'],
  'Damage Inc.': ['adam boqvist_D', 'brady tkachuk_F', 'dylan guenther_F', 'dylan strome_F', 'henry thrun_D', 'ivan barbashev_F', 'jordan kyrou_F', 'kevin bahl_D', 'mathew barzal_F', 'niko mikkola_D', 'philip broberg_D', 'samuel montembeault_G', 'simon nemec_D'],
  'Dumb and Goalie To': ['cole caufield_F', 'dmitri voronkov_F', 'jack roslovic_F', 'jakob chychrun_D', 'jeff skinner_F', 'jiri kulich_F', 'josh doan_F', 'mackenzie blackwood_G', 'mikael granlund_F', 'morgan geekie_F', 'oliver ekmanlarsson_D', 'paul cotter_F', 'seamus casey_D', 'sean monahan_F'],
  'Killer Whales': ['anton lundell_F', 'anze kopitar_F', 'auston matthews_F', 'braden schneider_D', 'dustin wolf_G', 'dylan holloway_F', 'emil andrae_D', 'fabian zetterlund_F', 'jacob markstrom_G', 'matt grzelcyk_D', 'miro heiskanen_D', 'nazem kadri_F', 'samuel girard_D', 'ty emberson_D', 'uvis balinskis_D', 'will smith_F'],
  'Motor City Wings': ['alex lyon_G', 'connor mcmichael_F', 'gabriel vilardi_F', 'jake walman_D', 'marco kasper_F', 'mason lohrei_D', 'mats zuccarello_F', 'olen zellweger_D', 'pavel dorofeyev_F', 'ridly greig_F', 'teuvo teravainen_F', 'zach werenski_D'],
  'Muller Time!': ['aliaksei protas_F', 'auston matthews_F', 'bryan rust_F', 'carter yakemchuk_D', 'denton mateychuk_D', 'jj moser_D', 'justin barron_D', 'martin necas_F', 'matvei michkov_F', 'pavel dorofeyev_F', 'rickard rakell_F', 'roope hintz_F', 'rutger mcgroarty_F', 'shea theodore_D', 'zayne parekh_D'],
  'Pernicious Puckers': ['alex vlasic_D', 'arturs silovs_G', 'artyom levshunov_D', 'casey mittelstadt_F', 'declan chisholm_D', 'filip gustavsson_G', 'justus annunen_G', 'kent johnson_F', 'lane hutson_D', 'nick suzuki_F', 'simon edvinsson_D', 'thatcher demko_G', 'tim stutzle_F', 'tony deangelo_D', 'victor olofsson_F', 'will cuylle_F'],
  'Silence of the Lamb': ['charlie lindgren_G', 'conor garland_F', 'cutter gauthier_F', 'darren raddysh_D', 'evgeni malkin_F', 'jason zucker_F', 'joel eriksson ek_F', 'john carlson_D', 'kris letang_D', 'logan thompson_G', 'mark scheifele_F', 'mike reilly_D', 'nick perbix_D', 'nikolaj ehlers_F', 'rasmus andersson_D', 'roman josi_D', 'samuel ersson_G', 'travis sanheim_D'],
};
