// 26-27 season setup data: prior-season (25-26) final standings.
// Split out of roster_tracker.html to keep the main file size down; loaded via <script src> before the app script.

// 2025-26 final standings — determines draft order (rank 9 picks first)
const FINAL_STANDINGS_2526 = {
  'Bossy Posse':         {rank:1, pts:1157},
  'Pernicious Puckers':  {rank:2, pts:1136},
  'Motor City Wings':    {rank:3, pts:1134},
  'Silence of the Lamb': {rank:4, pts:1105},
  'Damage Inc.':         {rank:5, pts:1091},
  'Blue Line Bangers':   {rank:6, pts:1058},
  'Muller Time!':        {rank:7, pts:1055},
  'Dumb and Goalie To':  {rank:8, pts:1040},
  'Killer Whales':       {rank:9, pts:909},
};

// Cap overrides for players with no signed 26-27 contract yet, but who'll clearly command real
// money once they do — without this they'd fall through to the generic
// UNSIGNED_FALLBACK_CAP_2627 floor ($1M), understating their real cap impact. Found live
// 2026-08-25 via a user report that unsigned players were giving their PPTS to a roster for
// $0 (Zach Bolduc → Dumb and Goalie To). Same format as MANUAL_CAPS_2425/2526/2324 (yrStr is
// display-only, not read by assignCapFromSignings — left blank since none have signed yet).
const MANUAL_CAPS_2627 = {
  'adam fantilli_F':      { cap: 13.75, yrStr: '' }, // real signed value (2026-09-24), not a guess
  'alexander nikishin_D': { cap: 6,  yrStr: '' },
  'simon edvinsson_D':    { cap: 7,  yrStr: '' },
};

// Captured 2026-07 from the 465.l.97882 league (25-26 season, essentially done — no more moves
// expected before a new league key is created for 26-27) via /rosters.
// 25-26 final rosters — pre-drop starting state for 26-27 simulation. Keys = normName.toLowerCase().
const PREDROP_ROSTER_2627 = {
  // Blue Line Bangers (20 players)
  'jack eichel':'Blue Line Bangers','macklin celebrini':'Blue Line Bangers','alex tuch':'Blue Line Bangers',
  'nico hischier':'Blue Line Bangers','adrian kempe':'Blue Line Bangers','adam fantilli':'Blue Line Bangers',
  'ivan demidov':'Blue Line Bangers','matt savoie':'Blue Line Bangers','sebastian aho_F':'Blue Line Bangers',
  'nick schmaltz':'Blue Line Bangers','artemi panarin':'Blue Line Bangers','pavel zacha':'Blue Line Bangers',
  'mackenzie weegar':'Blue Line Bangers','jordan spence':'Blue Line Bangers','mason lohrei':'Blue Line Bangers',
  'john marino':'Blue Line Bangers','sam malinski':'Blue Line Bangers','mike matheson':'Blue Line Bangers',
  'connor hellebuyck':'Blue Line Bangers','jakub dobes':'Blue Line Bangers',
  // Bossy Posse (20 players)
  'ryan nugenthopkins':'Bossy Posse','kyle connor':'Bossy Posse','tage thompson':'Bossy Posse',
  'juraj slafkovsky':'Bossy Posse','nathan mackinnon':'Bossy Posse','joel eriksson ek':'Bossy Posse',
  'mavrik bourque':'Bossy Posse','gabriel vilardi':'Bossy Posse','trevor zegras':'Bossy Posse',
  'emil heineman':'Bossy Posse','mika zibanejad':'Bossy Posse','gabe perreault':'Bossy Posse',
  'jackson lacombe':'Bossy Posse','evan bouchard':'Bossy Posse','sam dickinson':'Bossy Posse',
  'matthew schaefer':'Bossy Posse','matt grzelcyk':'Bossy Posse','ryker evans':'Bossy Posse',
  'jet greaves':'Bossy Posse','ilya sorokin':'Bossy Posse',
  // Damage Inc. (20 players)
  'mikko rantanen':'Damage Inc.','nikita kucherov':'Damage Inc.','brayden point':'Damage Inc.',
  'dylan guenther':'Damage Inc.','matt boldy':'Damage Inc.','dylan strome':'Damage Inc.',
  'drake batherson':'Damage Inc.','kirill marchenko':'Damage Inc.','leo carlsson':'Damage Inc.',
  'beckett sennecke':'Damage Inc.','luke evangelista':'Damage Inc.','robert thomas':'Damage Inc.',
  'jake sanderson':'Damage Inc.','philip broberg':'Damage Inc.','simon nemec':'Damage Inc.',
  'logan mailloux':'Damage Inc.','ryan shea':'Damage Inc.','charleedouard dastous':'Damage Inc.',
  'brandon bussi':'Damage Inc.','lukas dostal':'Damage Inc.',
  // Dumb and Goalie To (20 players)
  'cole caufield':'Dumb and Goalie To','jack quinn':'Dumb and Goalie To','brandon hagel':'Dumb and Goalie To',
  'david pastrnak':'Dumb and Goalie To','morgan geekie':'Dumb and Goalie To','zachary bolduc':'Dumb and Goalie To',
  'claude giroux':'Dumb and Goalie To','marcus johansson':'Dumb and Goalie To','josh doan':'Dumb and Goalie To',
  'josh norris':'Dumb and Goalie To','brock nelson':'Dumb and Goalie To','egor chinakhov':'Dumb and Goalie To',
  'cale makar':'Dumb and Goalie To','thomas harley':'Dumb and Goalie To','nick blankenburg':'Dumb and Goalie To',
  'rasmus dahlin':'Dumb and Goalie To','shayne gostisbehere':'Dumb and Goalie To','parker wotherspoon':'Dumb and Goalie To',
  'mackenzie blackwood':'Dumb and Goalie To','yaroslav askarov':'Dumb and Goalie To',
  // Killer Whales (20 players)
  'william eklund':'Killer Whales','will smith':'Killer Whales','jack hughes':'Killer Whales',
  'seth jarvis':'Killer Whales','quinton byfield':'Killer Whales','cole perfetti':'Killer Whales',
  'connor bedard':'Killer Whales','frank nazar':'Killer Whales','mason mctavish':'Killer Whales',
  'igor chernyshov':'Killer Whales','matthew wood':'Killer Whales','matvei gridin':'Killer Whales',
  'josh morrissey':'Killer Whales','jamie drysdale':'Killer Whales','morgan rielly':'Killer Whales',
  'john klingberg':'Killer Whales','jakob chychrun':'Killer Whales','sean durzi':'Killer Whales',
  'dustin wolf':'Killer Whales','spencer knight':'Killer Whales',
  // Motor City Wings (20 players)
  'sidney crosby':'Motor City Wings','kirill kaprizov':'Motor City Wings','clayton keller':'Motor City Wings',
  'jake guentzel':'Motor City Wings','dylan larkin':'Motor City Wings','lucas raymond':'Motor City Wings',
  'pavel dorofeyev':'Motor City Wings','jimmy snuggerud':'Motor City Wings','ben kindel':'Motor City Wings',
  'rickard rakell':'Motor City Wings','ryan oreilly':'Motor City Wings','dylan holloway':'Motor City Wings',
  'zach werenski':'Motor City Wings','brent burns':'Motor City Wings','brandt clarke':'Motor City Wings',
  'olen zellweger':'Motor City Wings','tom willander':'Motor City Wings','sam rinzel':'Motor City Wings',
  'jake oettinger':'Motor City Wings','john gibson':'Motor City Wings',
  // Muller Time! (20 players)
  'mitch marner':'Muller Time!','martin necas':'Muller Time!','wyatt johnston':'Muller Time!',
  'matvei michkov':'Muller Time!','logan cooley':'Muller Time!','vincent trocheck':'Muller Time!',
  'bryan rust':'Muller Time!','aliaksei protas':'Muller Time!','ryan leonard':'Muller Time!',
  'mark stone':'Muller Time!','zach hyman':'Muller Time!','oliver kapanen':'Muller Time!',
  'zayne parekh':'Muller Time!','zeev buium':'Muller Time!','denton mateychuk':'Muller Time!',
  'miro heiskanen':'Muller Time!','john carlson':'Muller Time!','carter yakemchuk':'Muller Time!',
  'karel vejmelka':'Muller Time!','jacob fowler':'Muller Time!',
  // Pernicious Puckers (20 players)
  'leon draisaitl':'Pernicious Puckers','tim stutzle':'Pernicious Puckers','nick suzuki':'Pernicious Puckers',
  'alex debrincat':'Pernicious Puckers','jason robertson':'Pernicious Puckers','alexis lafreniere':'Pernicious Puckers',
  'marco rossi':'Pernicious Puckers','john tavares':'Pernicious Puckers','mats zuccarello':'Pernicious Puckers',
  'danila yurov':'Pernicious Puckers','jackson blake':'Pernicious Puckers','emmitt finnie':'Pernicious Puckers',
  'quinn hughes':'Pernicious Puckers','tony deangelo':'Pernicious Puckers','artyom levshunov':'Pernicious Puckers',
  'lane hutson':'Pernicious Puckers','simon edvinsson':'Pernicious Puckers','jake walman':'Pernicious Puckers',
  'filip gustavsson':'Pernicious Puckers','jesper wallstedt':'Pernicious Puckers',
  // Silence of the Lamb (20 players)
  'connor mcdavid':'Silence of the Lamb','brad marchand':'Silence of the Lamb','matthew knies':'Silence of the Lamb',
  'cutter gauthier':'Silence of the Lamb','jesper bratt':'Silence of the Lamb','matt duchene':'Silence of the Lamb',
  'patrick kane':'Silence of the Lamb','mark scheifele':'Silence of the Lamb','michael misa':'Silence of the Lamb',
  'troy terry':'Silence of the Lamb','tyler bertuzzi':'Silence of the Lamb','ivan barbashev':'Silence of the Lamb',
  'pavel mintyukov':'Silence of the Lamb','rasmus andersson':'Silence of the Lamb','darren raddysh':'Silence of the Lamb',
  'alexander nikishin':'Silence of the Lamb','mattias samuelsson':'Silence of the Lamb','filip hronek':'Silence of the Lamb',
  'logan thompson':'Silence of the Lamb','scott wedgewood':'Silence of the Lamb',
};

const PREDROP_STUBS_2627 = [
  {name:'Mikko Rantanen', pos:'F'},
  {name:'Nikita Kucherov', pos:'F'},
  {name:'Brayden Point', pos:'F'},
  {name:'Dylan Guenther', pos:'F'},
  {name:'Matt Boldy', pos:'F'},
  {name:'Dylan Strome', pos:'F'},
  {name:'Drake Batherson', pos:'F'},
  {name:'Kirill Marchenko', pos:'F'},
  {name:'Leo Carlsson', pos:'F'},
  {name:'Beckett Sennecke', pos:'F'},
  {name:'Luke Evangelista', pos:'F'},
  {name:'Robert Thomas', pos:'F'},
  {name:'Jake Sanderson', pos:'D'},
  {name:'Philip Broberg', pos:'D'},
  {name:'Simon Nemec', pos:'D'},
  {name:'Logan Mailloux', pos:'D'},
  {name:'Ryan Shea', pos:'D'},
  {name:"Charle-Edouard D'Astous", pos:'D'},
  {name:'Brandon Bussi', pos:'G'},
  {name:'Lukas Dostal', pos:'G'},
  {name:'Jack Eichel', pos:'F'},
  {name:'Macklin Celebrini', pos:'F'},
  {name:'Alex Tuch', pos:'F'},
  {name:'Nico Hischier', pos:'F'},
  {name:'Adrian Kempe', pos:'F'},
  {name:'Adam Fantilli', pos:'F'},
  {name:'Ivan Demidov', pos:'F'},
  {name:'Matt Savoie', pos:'F'},
  {name:'Sebastian Aho', pos:'F'},
  {name:'Nick Schmaltz', pos:'F'},
  {name:'Artemi Panarin', pos:'F'},
  {name:'Pavel Zacha', pos:'F'},
  {name:'MacKenzie Weegar', pos:'D'},
  {name:'Jordan Spence', pos:'D'},
  {name:'Mason Lohrei', pos:'D'},
  {name:'John Marino', pos:'D'},
  {name:'Sam Malinski', pos:'D'},
  {name:'Mike Matheson', pos:'D'},
  {name:'Connor Hellebuyck', pos:'G'},
  {name:'Jakub Dobes', pos:'G'},
  {name:'Ryan Nugent-Hopkins', pos:'F'},
  {name:'Kyle Connor', pos:'F'},
  {name:'Tage Thompson', pos:'F'},
  {name:'Juraj Slafkovský', pos:'F'},
  {name:'Nathan MacKinnon', pos:'F'},
  {name:'Joel Eriksson Ek', pos:'F'},
  {name:'Mavrik Bourque', pos:'F'},
  {name:'Gabriel Vilardi', pos:'F'},
  {name:'Trevor Zegras', pos:'F'},
  {name:'Emil Heineman', pos:'F'},
  {name:'Mika Zibanejad', pos:'F'},
  {name:'Gabe Perreault', pos:'F'},
  {name:'Jackson LaCombe', pos:'D'},
  {name:'Evan Bouchard', pos:'D'},
  {name:'Sam Dickinson', pos:'D'},
  {name:'Matthew Schaefer', pos:'D'},
  {name:'Matt Grzelcyk', pos:'D'},
  {name:'Ryker Evans', pos:'D'},
  {name:'Jet Greaves', pos:'G'},
  {name:'Ilya Sorokin', pos:'G'},
  {name:'Cole Caufield', pos:'F'},
  {name:'Jack Quinn', pos:'F'},
  {name:'Brandon Hagel', pos:'F'},
  {name:'David Pastrnak', pos:'F'},
  {name:'Morgan Geekie', pos:'F'},
  {name:'Zachary Bolduc', pos:'F'},
  {name:'Claude Giroux', pos:'F'},
  {name:'Marcus Johansson', pos:'F'},
  {name:'Josh Doan', pos:'F'},
  {name:'Josh Norris', pos:'F'},
  {name:'Brock Nelson', pos:'F'},
  {name:'Egor Chinakhov', pos:'F'},
  {name:'Cale Makar', pos:'D'},
  {name:'Thomas Harley', pos:'D'},
  {name:'Nick Blankenburg', pos:'D'},
  {name:'Rasmus Dahlin', pos:'D'},
  {name:'Shayne Gostisbehere', pos:'D'},
  {name:'Parker Wotherspoon', pos:'D'},
  {name:'Mackenzie Blackwood', pos:'G'},
  {name:'Yaroslav Askarov', pos:'G'},
  {name:'William Eklund', pos:'F'},
  {name:'Will Smith', pos:'F'},
  {name:'Jack Hughes', pos:'F'},
  {name:'Seth Jarvis', pos:'F'},
  {name:'Quinton Byfield', pos:'F'},
  {name:'Cole Perfetti', pos:'F'},
  {name:'Connor Bedard', pos:'F'},
  {name:'Frank Nazar', pos:'F'},
  {name:'Mason McTavish', pos:'F'},
  {name:'Igor Chernyshov', pos:'F'},
  {name:'Matthew Wood', pos:'F'},
  {name:'Matvei Gridin', pos:'F'},
  {name:'Josh Morrissey', pos:'D'},
  {name:'Jamie Drysdale', pos:'D'},
  {name:'Morgan Rielly', pos:'D'},
  {name:'John Klingberg', pos:'D'},
  {name:'Jakob Chychrun', pos:'D'},
  {name:'Sean Durzi', pos:'D'},
  {name:'Dustin Wolf', pos:'G'},
  {name:'Spencer Knight', pos:'G'},
  {name:'Sidney Crosby', pos:'F'},
  {name:'Kirill Kaprizov', pos:'F'},
  {name:'Clayton Keller', pos:'F'},
  {name:'Jake Guentzel', pos:'F'},
  {name:'Dylan Larkin', pos:'F'},
  {name:'Lucas Raymond', pos:'F'},
  {name:'Pavel Dorofeyev', pos:'F'},
  {name:'Jimmy Snuggerud', pos:'F'},
  {name:'Ben Kindel', pos:'F'},
  {name:'Rickard Rakell', pos:'F'},
  {name:"Ryan O'Reilly", pos:'F'},
  {name:'Dylan Holloway', pos:'F'},
  {name:'Zach Werenski', pos:'D'},
  {name:'Brent Burns', pos:'D'},
  {name:'Brandt Clarke', pos:'D'},
  {name:'Olen Zellweger', pos:'D'},
  {name:'Tom Willander', pos:'D'},
  {name:'Sam Rinzel', pos:'D'},
  {name:'Jake Oettinger', pos:'G'},
  {name:'John Gibson', pos:'G'},
  {name:'Mitch Marner', pos:'F'},
  {name:'Martin Necas', pos:'F'},
  {name:'Wyatt Johnston', pos:'F'},
  {name:'Matvei Michkov', pos:'F'},
  {name:'Logan Cooley', pos:'F'},
  {name:'Vincent Trocheck', pos:'F'},
  {name:'Bryan Rust', pos:'F'},
  {name:'Aliaksei Protas', pos:'F'},
  {name:'Ryan Leonard', pos:'F'},
  {name:'Mark Stone', pos:'F'},
  {name:'Zach Hyman', pos:'F'},
  {name:'Oliver Kapanen', pos:'F'},
  {name:'Zayne Parekh', pos:'D'},
  {name:'Zeev Buium', pos:'D'},
  {name:'Denton Mateychuk', pos:'D'},
  {name:'Miro Heiskanen', pos:'D'},
  {name:'John Carlson', pos:'D'},
  {name:'Carter Yakemchuk', pos:'D'},
  {name:'Karel Vejmelka', pos:'G'},
  {name:'Jacob Fowler', pos:'G'},
  {name:'Leon Draisaitl', pos:'F'},
  {name:'Tim Stutzle', pos:'F'},
  {name:'Nick Suzuki', pos:'F'},
  {name:'Alex DeBrincat', pos:'F'},
  {name:'Jason Robertson', pos:'F'},
  {name:'Alexis Lafreniere', pos:'F'},
  {name:'Marco Rossi', pos:'F'},
  {name:'John Tavares', pos:'F'},
  {name:'Mats Zuccarello', pos:'F'},
  {name:'Danila Yurov', pos:'F'},
  {name:'Jackson Blake', pos:'F'},
  {name:'Emmitt Finnie', pos:'F'},
  {name:'Quinn Hughes', pos:'D'},
  {name:'Tony DeAngelo', pos:'D'},
  {name:'Artyom Levshunov', pos:'D'},
  {name:'Lane Hutson', pos:'D'},
  {name:'Simon Edvinsson', pos:'D'},
  {name:'Jake Walman', pos:'D'},
  {name:'Filip Gustavsson', pos:'G'},
  {name:'Jesper Wallstedt', pos:'G'},
  {name:'Connor McDavid', pos:'F'},
  {name:'Brad Marchand', pos:'F'},
  {name:'Matthew Knies', pos:'F'},
  {name:'Cutter Gauthier', pos:'F'},
  {name:'Jesper Bratt', pos:'F'},
  {name:'Matt Duchene', pos:'F'},
  {name:'Patrick Kane', pos:'F'},
  {name:'Mark Scheifele', pos:'F'},
  {name:'Michael Misa', pos:'F'},
  {name:'Troy Terry', pos:'F'},
  {name:'Tyler Bertuzzi', pos:'F'},
  {name:'Ivan Barbashev', pos:'F'},
  {name:'Pavel Mintyukov', pos:'D'},
  {name:'Rasmus Andersson', pos:'D'},
  {name:'Darren Raddysh', pos:'D'},
  {name:'Alexander Nikishin', pos:'D'},
  {name:'Mattias Samuelsson', pos:'D'},
  {name:'Filip Hronek', pos:'D'},
  {name:'Logan Thompson', pos:'G'},
  {name:'Scott Wedgewood', pos:'G'},
];

// Real 26-27 preseason draft — recorded 2026-10-03 from the live draft's Export Draft CSV
// (hghl_draft_2627_2026-10-03.csv), after the live UI froze mid-draft (see
// project_live_draft_recovery memory for the Anton Johansson/savePlayer-mid-draft root cause
// and recovery steps). KIL's roster situation post-draft put them over the cap — see that same
// memory for the real resolution (burning a midseason replacement).
const POSTDRAFT_ROSTER_2627 = {
  // Killer Whales (8 picks)
  'gavin mckenna':'Killer Whales',  // R1
  'mackenzie blackwood':'Killer Whales',  // R2
  'miro heiskanen':'Killer Whales',  // R3
  'olen zellweger':'Killer Whales',  // R4
  'anton johansson':'Killer Whales',  // R5 — real NHL player (DET, D, $0.97M), added to the
                                       // database live (see project_live_draft_recovery memory)
  'kent johnson':'Killer Whales',  // R6
  'cutter gauthier':'Killer Whales',  // R7
  'mikhail sergachev':'Killer Whales',  // R8 — put KIL over the cap, recorded as-is per the
                                         // real draft; cap fix is a real-world midseason move
  // Dumb and Goalie To (9 picks)
  'porter martone':'Dumb and Goalie To',  // R1
  'james hagens':'Dumb and Goalie To',  // R2
  'juuse saros':'Dumb and Goalie To',  // R3
  'konsta helenius':'Dumb and Goalie To',  // R4
  'charlie mcavoy':'Dumb and Goalie To',  // R5
  'sam malinski':'Dumb and Goalie To',  // R6
  'vincent trocheck':'Dumb and Goalie To',  // R7
  'mason marchment':'Dumb and Goalie To',  // R8
  'vince dunn':'Dumb and Goalie To',  // R9
  // Muller Time! (5 picks)
  'cole hutson':'Muller Time!',  // R1
  'jeremy swayman':'Muller Time!',  // R2
  'matthew knies':'Muller Time!',  // R3
  'marco rossi':'Muller Time!',  // R4
  'victor eklund':'Muller Time!',  // R5
  // Blue Line Bangers (10 picks)
  'anton frondell':'Blue Line Bangers',  // R1
  'adam fox':'Blue Line Bangers',  // R2
  'rasmus dahlin':'Blue Line Bangers',  // R3
  'shea theodore':'Blue Line Bangers',  // R4
  'shane wright':'Blue Line Bangers',  // R5
  'theo lindstein':'Blue Line Bangers',  // R6
  'ryan hartman':'Blue Line Bangers',  // R7
  'simon holmstrom':'Blue Line Bangers',  // R8
  'jamie benn':'Blue Line Bangers',  // R9
  'sean walker':'Blue Line Bangers',  // R10
  // Damage Inc. (6 picks)
  'luca cagnoni':'Damage Inc.',  // R1
  'axel sandin pellikka':'Damage Inc.',  // R2
  'ryan ufko':'Damage Inc.',  // R3
  'william nylander':'Damage Inc.',  // R4
  'matthew tkachuk':'Damage Inc.',  // R5
  'drew helleson':'Damage Inc.',  // R6
  // Silence of the Lamb (6 picks)
  'ivar stenberg':'Silence of the Lamb',  // R1
  'roman kantserov':'Silence of the Lamb',  // R2
  'oliver ekmanlarsson':'Silence of the Lamb',  // R3
  'mattias ekholm':'Silence of the Lamb',  // R4
  'john marino':'Silence of the Lamb',  // R5
  'alex ovechkin':'Silence of the Lamb',  // R6
  // Motor City Wings (5 picks)
  'carter hart':'Motor City Wings',  // R1
  'evgeni malkin':'Motor City Wings',  // R2
  'jared mccann':'Motor City Wings',  // R3
  'roman josi':'Motor City Wings',  // R4
  'tj hughes':'Motor City Wings',  // R5
  // Pernicious Puckers (6 picks)
  'moritz seider':'Pernicious Puckers',  // R1
  'bowen byram':'Pernicious Puckers',  // R2
  'ilya protas':'Pernicious Puckers',  // R3
  'viggo bjorck':'Pernicious Puckers',  // R4
  'tristan luneau':'Pernicious Puckers',  // R5
  'arturs silovs':'Pernicious Puckers',  // R6
  // Bossy Posse (5 picks)
  'adam jiricek':'Bossy Posse',  // R1
  'easton cowan':'Bossy Posse',  // R2
  'joel hofer':'Bossy Posse',  // R3
  'dmitri simashev':'Bossy Posse',  // R4
  'calum ritchie':'Bossy Posse',  // R5
};

// Real NHL per-player fantasy points/games-played as of the night before the 26-27 preseason
// draft (games through 2026-10-01, i.e. before draftDatePreseason2627) — memorializes the
// state of the NHL on draft night so future draft-night simulations can be re-run against it,
// independent of the live pts2627/gp2627 fields (which keep moving as syncStats2627() re-pulls
// current totals). Reconstructed 2026-10-06 via Yahoo's own per-date player stats (NOT NHL.com's
// public API, which rate-limits per-player game-log requests too hard to be practical) —
// this league's Yahoo scoring (Goals=1, Assists=1, Wins=2, Shutouts=3, confirmed live via
// /settings) is an exact match for our fpts formula, so Yahoo's per-day totals for
// 2026-09-29/09-30/10-01 were summed directly. pts/gp mirror the live pts2627/gp2627 field
// shape (not broken out into goals/assists/wins/shutouts) to keep this compact.
const NHL_STATS_ASOF_DRAFT_2627 = {
  'aaron ekblad_D': {pts:1, gp:2},
  'adam edstrom_F': {pts:0, gp:1},
  'adam fantilli_F': {pts:1, gp:1},
  'adam fox_D': {pts:2, gp:2},
  'adam klapka_F': {pts:0, gp:1},
  'adam larsson_D': {pts:0, gp:1},
  'adam pelech_D': {pts:0, gp:1},
  'adam wilsby_D': {pts:0, gp:1},
  'adrian kempe_F': {pts:0, gp:1},
  'akira schmid_G': {pts:0, gp:1},
  'alberts smits_D': {pts:0, gp:2},
  'aleksander barkov_F': {pts:0, gp:2},
  'alex bump_F': {pts:0, gp:2},
  'alex carrier_D': {pts:2, gp:1},
  'alex formenton_F': {pts:1, gp:2},
  'alex kerfoot_F': {pts:0, gp:1},
  'alex laferriere_F': {pts:2, gp:1},
  'alex newhook_F': {pts:0, gp:1},
  'alex romanov_D': {pts:0, gp:1},
  'alex texier_F': {pts:0, gp:1},
  'alex turcotte_F': {pts:1, gp:1},
  'alex vlasic_D': {pts:0, gp:2},
  'alex wennberg_F': {pts:0, gp:1},
  'alexander kerfoot_F': {pts:0, gp:1},
  'alexander romanov_D': {pts:0, gp:1},
  'alexander wennberg_F': {pts:0, gp:1},
  'alexandre bump_F': {pts:0, gp:2},
  'alexandre carrier_D': {pts:2, gp:1},
  'alexandre formenton_F': {pts:1, gp:2},
  'alexandre laferriere_F': {pts:2, gp:1},
  'alexandre newhook_F': {pts:0, gp:1},
  'alexandre texier_F': {pts:0, gp:1},
  'alexandre turcotte_F': {pts:1, gp:1},
  'alexandre vlasic_D': {pts:0, gp:2},
  'alexis lafreniere_F': {pts:0, gp:2},
  'amadeus lombardi_F': {pts:0, gp:1},
  'anders lee_F': {pts:1, gp:1},
  'andre lee_F': {pts:0, gp:1},
  'andrei svechnikov_F': {pts:0, gp:1},
  'andrei vasilevskiy_G': {pts:0, gp:1},
  'andrew mangiapane_F': {pts:0, gp:1},
  'andrew peeke_D': {pts:1, gp:1},
  'anthony cirelli_F': {pts:0, gp:1},
  'anthony duclair_F': {pts:0, gp:1},
  'anthony mantha_F': {pts:0, gp:1},
  'anthony stolarz_G': {pts:2, gp:1},
  'anton frondell_F': {pts:0, gp:2},
  'anton lundell_F': {pts:1, gp:2},
  'arber xhekaj_D': {pts:0, gp:1},
  'arseny gritsyuk_F': {pts:0, gp:1},
  'arshdeep bains_F': {pts:2, gp:2},
  'artem levshunov_D': {pts:0, gp:2},
  'artemi panarin_F': {pts:1, gp:1},
  'artturi lehkonen_F': {pts:2, gp:1},
  'arturs silovs_G': {pts:5, gp:1},
  'artyom levshunov_D': {pts:0, gp:2},
  'arvid soderblom_G': {pts:0, gp:1},
  'auston matthews_F': {pts:0, gp:2},
  'barclay goodrow_F': {pts:0, gp:1},
  'barrett hayton_F': {pts:0, gp:1},
  'beck malenstyn_F': {pts:0, gp:1},
  'berkly catton_F': {pts:0, gp:1},
  'blake coleman_F': {pts:1, gp:1},
  'blake lizotte_F': {pts:0, gp:1},
  'bo groulx_F': {pts:0, gp:1},
  'bo horvat_F': {pts:1, gp:1},
  'bobby brink_F': {pts:1, gp:1},
  'bobby mcmann_F': {pts:0, gp:1},
  'bokondji imama_F': {pts:0, gp:2},
  'bowen byram_D': {pts:0, gp:2},
  'braden schneider_D': {pts:0, gp:2},
  'brady skjei_D': {pts:0, gp:1},
  'brady tkachuk_F': {pts:0, gp:2},
  'braeden bowman_F': {pts:0, gp:1},
  'brandon bussi_G': {pts:0, gp:1},
  'brandon duhaime_F': {pts:0, gp:2},
  'brandon hagel_F': {pts:0, gp:1},
  'brandon montour_D': {pts:0, gp:1},
  'brandt clarke_D': {pts:0, gp:1},
  'brayden mcnabb_D': {pts:2, gp:1},
  'brayden point_F': {pts:1, gp:1},
  'brayden schenn_F': {pts:0, gp:1},
  'brendan gallagher_F': {pts:0, gp:2},
  'brenden dillon_D': {pts:0, gp:1},
  'brent burns_D': {pts:1, gp:1},
  'brett howden_F': {pts:0, gp:1},
  'brett kulak_D': {pts:0, gp:1},
  'brett pesce_D': {pts:0, gp:1},
  'brian dumoulin_D': {pts:1, gp:1},
  'brock boeser_F': {pts:3, gp:2},
  'brock nelson_F': {pts:3, gp:1},
  'cale makar_D': {pts:2, gp:1},
  'calum ritchie_F': {pts:0, gp:1},
  'cam york_D': {pts:0, gp:2},
  'cameron york_D': {pts:0, gp:2},
  'carl grundstrom_F': {pts:0, gp:2},
  'carson soucy_D': {pts:0, gp:1},
  'carter hart_G': {pts:2, gp:1},
  'carter verhaeghe_F': {pts:1, gp:2},
  'casey cizikas_F': {pts:0, gp:1},
  'casey mittelstadt_F': {pts:0, gp:1},
  'chandler stephenson_F': {pts:1, gp:1},
  'charleedouard dastous_D': {pts:0, gp:1},
  'charles alexis legault_D': {pts:0, gp:1},
  'charlie coyle_F': {pts:3, gp:1},
  'chris kreider_F': {pts:0, gp:1},
  'chris tanev_D': {pts:0, gp:2},
  'christian dvorak_F': {pts:0, gp:2},
  'christopher kreider_F': {pts:0, gp:1},
  'christopher tanev_D': {pts:0, gp:2},
  'clayton keller_F': {pts:2, gp:1},
  'cody ceci_D': {pts:1, gp:1},
  'cody glass_F': {pts:0, gp:1},
  'cole caufield_F': {pts:0, gp:1},
  'cole sillinger_F': {pts:1, gp:1},
  'cole smith_F': {pts:0, gp:2},
  'collin graf_F': {pts:0, gp:1},
  'colton dach_F': {pts:0, gp:2},
  'colton sissons_F': {pts:1, gp:2},
  'connor clifton_D': {pts:0, gp:1},
  'connor dewar_F': {pts:0, gp:1},
  'connor mcdavid_F': {pts:7, gp:2},
  'connor murphy_D': {pts:0, gp:2},
  'connor zary_F': {pts:1, gp:1},
  'conor garland_F': {pts:0, gp:1},
  'conor geekie_F': {pts:0, gp:1},
  'curtis douglas_F': {pts:0, gp:1},
  'daemon hunt_D': {pts:0, gp:1},
  'dan vladar_G': {pts:0, gp:1},
  'daniel vladar_G': {pts:0, gp:1},
  'daniil but_F': {pts:1, gp:1},
  'danila yurov_F': {pts:1, gp:1},
  'danton heinen_F': {pts:0, gp:1},
  'darcy kuemper_G': {pts:0, gp:1},
  'darnell nurse_D': {pts:0, gp:1},
  'darren raddysh_D': {pts:0, gp:2},
  'dave pastrnak_F': {pts:0, gp:1},
  'david pastrnak_F': {pts:0, gp:1},
  'dawson mercer_F': {pts:0, gp:1},
  'declan carlile_D': {pts:1, gp:1},
  'declan chisholm_D': {pts:0, gp:1},
  'denton mateychuk_D': {pts:1, gp:1},
  'devon levi_G': {pts:2, gp:1},
  'devon toews_D': {pts:2, gp:1},
  'dmitri simashev_D': {pts:1, gp:1},
  'dmitri voronkov_F': {pts:1, gp:1},
  'dmitry kulikov_D': {pts:1, gp:2},
  'dmitry orlov_D': {pts:0, gp:1},
  'dougie hamilton_D': {pts:1, gp:1},
  'drew doughty_D': {pts:1, gp:1},
  'drew oconnor_F': {pts:1, gp:2},
  'dustin wolf_G': {pts:0, gp:1},
  'dylan guenther_F': {pts:2, gp:1},
  'easton cowan_F': {pts:3, gp:2},
  'eeli tolvanen_F': {pts:1, gp:2},
  'eetu luostarinen_F': {pts:2, gp:2},
  'egor chinakhov_F': {pts:1, gp:1},
  'egor sharangovich_F': {pts:1, gp:1},
  'elias lindholm_F': {pts:1, gp:1},
  'elias pettersson_D': {pts:0, gp:2},
  'elmer soderblom_F': {pts:0, gp:1},
  'emil andrae_D': {pts:1, gp:1},
  'emil heineman_F': {pts:1, gp:1},
  'eric robinson_F': {pts:0, gp:1},
  'erik cernak_D': {pts:0, gp:1},
  'erik gudbranson_D': {pts:0, gp:1},
  'erik haula_F': {pts:1, gp:1},
  'erik karlsson_D': {pts:1, gp:1},
  'evan bouchard_D': {pts:8, gp:2},
  'evan rodrigues_F': {pts:0, gp:1},
  'evgeni malkin_F': {pts:1, gp:1},
  'fedor svechkov_F': {pts:0, gp:1},
  'filip forsberg_F': {pts:1, gp:1},
  'filip hallander_F': {pts:3, gp:1},
  'filip hronek_D': {pts:4, gp:2},
  'frank nazar_F': {pts:0, gp:2},
  'fraser minten_F': {pts:2, gp:1},
  'freddy gaudreau_F': {pts:1, gp:1},
  'fyodor svechkov_F': {pts:0, gp:1},
  'gabe landeskog_F': {pts:1, gp:1},
  'gabe perreault_F': {pts:1, gp:2},
  'gabriel landeskog_F': {pts:1, gp:1},
  'gabriel perreault_F': {pts:1, gp:2},
  'gage goncalves_F': {pts:0, gp:1},
  'garnet hathaway_F': {pts:0, gp:2},
  'gavin mckenna_F': {pts:0, gp:2},
  'gustav forsling_D': {pts:1, gp:1},
  'hampus lindholm_D': {pts:1, gp:1},
  'hendrix lapierre_F': {pts:2, gp:1},
  'ian cole_D': {pts:0, gp:2},
  'igor chernyshov_F': {pts:0, gp:1},
  'igor shesterkin_G': {pts:2, gp:2},
  'ilya mikheyev_F': {pts:1, gp:1},
  'ilya sorokin_G': {pts:0, gp:1},
  'isaac howard_F': {pts:1, gp:2},
  'ivan barbashev_F': {pts:2, gp:1},
  'ivan demidov_F': {pts:0, gp:1},
  'ivar stenberg_F': {pts:0, gp:1},
  'jaccob slavin_D': {pts:0, gp:1},
  'jack carlson_D': {pts:0, gp:1},
  'jack drury_F': {pts:0, gp:1},
  'jack eichel_F': {pts:3, gp:1},
  'jack hughes_F': {pts:1, gp:1},
  'jack marino_D': {pts:0, gp:1},
  'jack mcbain_F': {pts:0, gp:1},
  'jack quinn_F': {pts:1, gp:1},
  'jack roslovic_F': {pts:1, gp:2},
  'jack tavares_F': {pts:1, gp:2},
  'jackson blake_F': {pts:0, gp:1},
  'jacob allen_G': {pts:2, gp:1},
  'jacob christiansen_D': {pts:0, gp:1},
  'jacob debrusk_F': {pts:1, gp:2},
  'jacob evans_F': {pts:0, gp:1},
  'jacob guentzel_F': {pts:0, gp:1},
  'jacob markstrom_G': {pts:5, gp:1},
  'jacob mccabe_D': {pts:0, gp:2},
  'jacob melanson_F': {pts:0, gp:1},
  'jacob middleton_D': {pts:0, gp:1},
  'jacob trouba_D': {pts:0, gp:1},
  'jacob walman_D': {pts:0, gp:2},
  'jaden schwartz_F': {pts:2, gp:1},
  'jake allen_G': {pts:2, gp:1},
  'jake christiansen_D': {pts:0, gp:1},
  'jake debrusk_F': {pts:1, gp:2},
  'jake evans_F': {pts:0, gp:1},
  'jake guentzel_F': {pts:0, gp:1},
  'jake markstrom_G': {pts:5, gp:1},
  'jake mccabe_D': {pts:0, gp:2},
  'jake melanson_F': {pts:0, gp:1},
  'jake middleton_D': {pts:0, gp:1},
  'jake trouba_D': {pts:0, gp:1},
  'jake walman_D': {pts:0, gp:2},
  'jakub dobes_G': {pts:2, gp:1},
  'jalen chatfield_D': {pts:0, gp:1},
  'james hagens_F': {pts:0, gp:1},
  'jamie drysdale_D': {pts:0, gp:2},
  'jamie oleksiak_D': {pts:3, gp:2},
  'jansen harkins_F': {pts:0, gp:1},
  'jared mccann_F': {pts:3, gp:1},
  'jared spurgeon_D': {pts:1, gp:1},
  'jaroslav chmelar_F': {pts:0, gp:1},
  'jayden struble_D': {pts:0, gp:1},
  'jeangabriel pageau_F': {pts:0, gp:1},
  'jeffrey viel_F': {pts:0, gp:1},
  'jeremy lauzon_D': {pts:0, gp:1},
  'jeremy swayman_G': {pts:5, gp:1},
  'jesper bratt_F': {pts:1, gp:1},
  'jesper wallstedt_G': {pts:2, gp:1},
  'jet greaves_G': {pts:2, gp:1},
  'jiri kulich_F': {pts:0, gp:1},
  'jj moser_D': {pts:0, gp:1},
  'jj peterka_F': {pts:1, gp:1},
  'joe veleno_F': {pts:0, gp:2},
  'joe woll_G': {pts:0, gp:1},
  'joel armia_F': {pts:1, gp:1},
  'joel edmundson_D': {pts:0, gp:1},
  'joel eriksson ek_F': {pts:0, gp:1},
  'joel farabee_F': {pts:0, gp:1},
  'joey daccord_G': {pts:2, gp:1},
  'john carlson_D': {pts:0, gp:1},
  'john drury_F': {pts:0, gp:1},
  'john eichel_F': {pts:3, gp:1},
  'john hughes_F': {pts:1, gp:1},
  'john marino_D': {pts:0, gp:1},
  'john mcbain_F': {pts:0, gp:1},
  'john quinn_F': {pts:1, gp:1},
  'john roslovic_F': {pts:1, gp:2},
  'john tavares_F': {pts:1, gp:2},
  'johnjason moser_D': {pts:0, gp:1},
  'johnjason peterka_F': {pts:1, gp:1},
  'jonas brodin_D': {pts:0, gp:1},
  'jonas siegenthaler_D': {pts:0, gp:1},
  'jonathan aspirot_D': {pts:0, gp:1},
  'jonathan lekkerimaki_F': {pts:2, gp:2},
  'jonathan marchessault_F': {pts:0, gp:1},
  'jordan eberle_F': {pts:1, gp:1},
  'jordan greenway_F': {pts:1, gp:2},
  'jordan martinook_F': {pts:0, gp:1},
  'jordan staal_F': {pts:0, gp:1},
  'joseph veleno_F': {pts:0, gp:2},
  'joseph woll_G': {pts:0, gp:1},
  'josh anderson_F': {pts:2, gp:1},
  'josh doan_F': {pts:0, gp:1},
  'josh mahura_D': {pts:0, gp:1},
  'josh manson_D': {pts:1, gp:1},
  'josh norris_F': {pts:0, gp:1},
  'josh samanski_F': {pts:0, gp:1},
  'joshua anderson_F': {pts:2, gp:1},
  'joshua doan_F': {pts:0, gp:1},
  'joshua mahura_D': {pts:0, gp:1},
  'joshua manson_D': {pts:1, gp:1},
  'joshua norris_F': {pts:0, gp:1},
  'joshua samanski_F': {pts:0, gp:1},
  'jt miller_F': {pts:0, gp:2},
  'juraj slafkovsky_F': {pts:0, gp:1},
  'juuse saros_G': {pts:0, gp:1},
  'kaapo kakko_F': {pts:2, gp:1},
  'kaedan korczak_D': {pts:2, gp:1},
  'kandre miller_D': {pts:0, gp:1},
  'karel vejmelka_G': {pts:5, gp:1},
  'kasperi kapanen_F': {pts:2, gp:2},
  'kent johnson_F': {pts:1, gp:1},
  'kevin bahl_D': {pts:0, gp:1},
  'kevin lankinen_G': {pts:2, gp:2},
  'kevin stenlund_F': {pts:1, gp:1},
  'kiefer sherwood_F': {pts:0, gp:1},
  'kirby dach_F': {pts:1, gp:1},
  'kirill kaprizov_F': {pts:1, gp:1},
  'kirill marchenko_F': {pts:1, gp:2},
  'konsta helenius_F': {pts:1, gp:1},
  'kris letang_D': {pts:1, gp:1},
  'kyle palmieri_F': {pts:0, gp:1},
  'lane hutson_D': {pts:0, gp:1},
  'lars eller_F': {pts:1, gp:2},
  'lawson crouse_F': {pts:1, gp:1},
  'leevi merilainen_G': {pts:0, gp:1},
  'leon draisaitl_F': {pts:4, gp:2},
  'liam ohgren_F': {pts:2, gp:2},
  'linus karlsson_F': {pts:1, gp:2},
  'logan cooley_F': {pts:1, gp:1},
  'logan stankoven_F': {pts:0, gp:1},
  'logan stanley_D': {pts:0, gp:1},
  'louis crevier_D': {pts:0, gp:1},
  'luca cagnoni_D': {pts:2, gp:1},
  'luke evangelista_F': {pts:1, gp:1},
  'luke hughes_D': {pts:1, gp:1},
  'luke schenn_D': {pts:1, gp:2},
  'mackenzie blackwood_G': {pts:2, gp:1},
  'mackenzie weegar_D': {pts:0, gp:1},
  'macklin celebrini_F': {pts:3, gp:1},
  'maksim jones_F': {pts:0, gp:2},
  'maksim sasson_F': {pts:2, gp:2},
  'marat khusnutdinov_F': {pts:1, gp:1},
  'marc gatcomb_F': {pts:1, gp:1},
  'marco rossi_F': {pts:4, gp:2},
  'marcus foligno_F': {pts:0, gp:1},
  'marcus pettersson_D': {pts:0, gp:2},
  'mark jankowski_F': {pts:0, gp:1},
  'mark kastelic_F': {pts:1, gp:1},
  'mark stone_F': {pts:1, gp:1},
  'martin necas_F': {pts:1, gp:1},
  'martin pospisil_F': {pts:0, gp:1},
  'mason lohrei_D': {pts:1, gp:1},
  'mason marchment_F': {pts:1, gp:1},
  'mathieu joseph_F': {pts:1, gp:2},
  'mathieu olivier_F': {pts:1, gp:1},
  'matias maccelli_F': {pts:0, gp:1},
  'mats zuccarello_F': {pts:0, gp:1},
  'matt boldy_F': {pts:0, gp:1},
  'matt coronato_F': {pts:0, gp:1},
  'matt grzelcyk_D': {pts:0, gp:1},
  'matt knies_F': {pts:3, gp:1},
  'matt rempe_F': {pts:0, gp:1},
  'matt schaefer_D': {pts:0, gp:1},
  'matt tkachuk_F': {pts:1, gp:2},
  'matt wood_F': {pts:0, gp:1},
  'matthew beniers_F': {pts:2, gp:1},
  'matthew boldy_F': {pts:0, gp:1},
  'matthew coronato_F': {pts:0, gp:1},
  'matthew grzelcyk_D': {pts:0, gp:1},
  'matthew knies_F': {pts:3, gp:1},
  'matthew rempe_F': {pts:0, gp:1},
  'matthew schaefer_D': {pts:0, gp:1},
  'matthew tkachuk_F': {pts:1, gp:2},
  'matthew wood_F': {pts:0, gp:1},
  'mattias ekholm_D': {pts:0, gp:2},
  'mattias samuelsson_D': {pts:1, gp:1},
  'matty beniers_F': {pts:2, gp:1},
  'matty knies_F': {pts:3, gp:1},
  'matty schaefer_D': {pts:0, gp:1},
  'matty tkachuk_F': {pts:1, gp:2},
  'matty wood_F': {pts:0, gp:1},
  'matvei gridin_F': {pts:0, gp:1},
  'matvei michkov_F': {pts:0, gp:2},
  'mavrik bourque_F': {pts:0, gp:1},
  'max jones_F': {pts:0, gp:2},
  'max sasson_F': {pts:2, gp:2},
  'max shabanov_F': {pts:0, gp:1},
  'max tsyplakov_F': {pts:0, gp:1},
  'maxim shabanov_F': {pts:0, gp:1},
  'maxim tsyplakov_F': {pts:0, gp:1},
  'michael carcone_F': {pts:2, gp:1},
  'michael kesselring_D': {pts:0, gp:1},
  'michael matheson_D': {pts:1, gp:1},
  'michael mccarron_F': {pts:1, gp:1},
  'michael misa_F': {pts:0, gp:1},
  'mika zibanejad_F': {pts:2, gp:2},
  'mikael backlund_F': {pts:0, gp:1},
  'mike carcone_F': {pts:2, gp:1},
  'mike kesselring_D': {pts:0, gp:1},
  'mike matheson_D': {pts:1, gp:1},
  'mike mccarron_F': {pts:1, gp:1},
  'mike misa_F': {pts:0, gp:1},
  'mikey anderson_D': {pts:1, gp:1},
  'mikhail sergachev_D': {pts:1, gp:1},
  'mitch marner_F': {pts:0, gp:1},
  'mitchell marner_F': {pts:0, gp:1},
  'morgan frost_F': {pts:0, gp:1},
  'morgan geekie_F': {pts:0, gp:1},
  'morgan rielly_D': {pts:2, gp:2},
  'nate schmidt_D': {pts:1, gp:1},
  'nathan mackinnon_F': {pts:2, gp:1},
  'nazem kadri_F': {pts:2, gp:1},
  'nic dowd_F': {pts:1, gp:1},
  'nicholas foligno_F': {pts:1, gp:1},
  'nicholas lardis_F': {pts:0, gp:2},
  'nicholas paul_F': {pts:1, gp:2},
  'nicholas perbix_D': {pts:0, gp:1},
  'nicholas robertson_F': {pts:2, gp:1},
  'nicholas schmaltz_F': {pts:1, gp:1},
  'nicholas seeler_D': {pts:0, gp:2},
  'nicholas suzuki_F': {pts:0, gp:1},
  'nick foligno_F': {pts:1, gp:1},
  'nick lardis_F': {pts:0, gp:2},
  'nick paul_F': {pts:1, gp:2},
  'nick perbix_D': {pts:0, gp:1},
  'nick robertson_F': {pts:2, gp:1},
  'nick schmaltz_F': {pts:1, gp:1},
  'nick seeler_D': {pts:0, gp:2},
  'nick suzuki_F': {pts:0, gp:1},
  'nico hischier_F': {pts:0, gp:1},
  'nicolas deslauriers_F': {pts:0, gp:1},
  'nicolas hague_D': {pts:0, gp:1},
  'nicolas roy_F': {pts:1, gp:1},
  'nikita kucherov_F': {pts:1, gp:1},
  'nikita zadorov_D': {pts:0, gp:1},
  'niko mikkola_D': {pts:0, gp:2},
  'nikolaj ehlers_F': {pts:0, gp:1},
  'nils hoglander_F': {pts:0, gp:1},
  'noah cates_F': {pts:0, gp:2},
  'noah dobson_D': {pts:0, gp:1},
  'noah hanifin_D': {pts:1, gp:1},
  'noah juulsen_D': {pts:0, gp:1},
  'noah laba_F': {pts:1, gp:2},
  'noah ostlund_F': {pts:2, gp:1},
  'noel acciari_F': {pts:0, gp:2},
  'nolan allan_D': {pts:0, gp:1},
  'oliver bjorkstrand_F': {pts:1, gp:2},
  'oliver ekmanlarsson_D': {pts:0, gp:2},
  'oliver moore_F': {pts:0, gp:2},
  'olli maatta_D': {pts:1, gp:1},
  'ondrej palat_F': {pts:0, gp:1},
  'owen michaels_F': {pts:1, gp:2},
  'owen power_D': {pts:2, gp:1},
  'owen tippett_F': {pts:0, gp:2},
  'parker kelly_F': {pts:2, gp:1},
  'parker wotherspoon_D': {pts:0, gp:1},
  'pat kane_F': {pts:1, gp:2},
  'patrick kane_F': {pts:1, gp:2},
  'paul cotter_F': {pts:4, gp:2},
  'pavel dorofeyev_F': {pts:2, gp:2},
  'pavel zacha_F': {pts:0, gp:1},
  'peyton krebs_F': {pts:0, gp:1},
  'phillip danault_F': {pts:0, gp:1},
  'pontus holmberg_F': {pts:0, gp:1},
  'porter martone_F': {pts:0, gp:2},
  'quinn hughes_D': {pts:1, gp:1},
  'quinton byfield_F': {pts:0, gp:1},
  'radko gudas_D': {pts:0, gp:2},
  'rasmus andersson_D': {pts:0, gp:1},
  'rasmus dahlin_D': {pts:0, gp:1},
  'rasmus ristolainen_D': {pts:1, gp:2},
  'reid schaefer_F': {pts:0, gp:1},
  'rickard rakell_F': {pts:1, gp:1},
  'roman josi_D': {pts:1, gp:1},
  'roman kantserov_F': {pts:0, gp:2},
  'ross colton_F': {pts:0, gp:1},
  'ryan donato_F': {pts:0, gp:2},
  'ryan greene_F': {pts:1, gp:2},
  'ryan hartman_F': {pts:0, gp:1},
  'ryan lindgren_D': {pts:0, gp:1},
  'ryan lomberg_F': {pts:0, gp:1},
  'ryan mcdonagh_D': {pts:0, gp:1},
  'ryan mcleod_F': {pts:1, gp:1},
  'ryan oreilly_F': {pts:0, gp:1},
  'ryan pulock_D': {pts:0, gp:1},
  'ryan shea_D': {pts:2, gp:2},
  'ryan strome_F': {pts:1, gp:1},
  'ryan ufko_D': {pts:0, gp:1},
  'ryan winterton_F': {pts:1, gp:1},
  'ryker evans_D': {pts:1, gp:1},
  'sam bennett_F': {pts:1, gp:2},
  'sam carrick_F': {pts:0, gp:1},
  'sam girard_D': {pts:2, gp:1},
  'sam helenius_F': {pts:0, gp:1},
  'sam honzek_F': {pts:0, gp:1},
  'sam malinski_D': {pts:0, gp:1},
  'sam reinhart_F': {pts:0, gp:2},
  'sam rinzel_D': {pts:0, gp:2},
  'samuel bennett_F': {pts:1, gp:2},
  'samuel carrick_F': {pts:0, gp:1},
  'samuel girard_D': {pts:2, gp:1},
  'samuel helenius_F': {pts:0, gp:1},
  'samuel honzek_F': {pts:0, gp:1},
  'samuel malinski_D': {pts:0, gp:1},
  'samuel reinhart_F': {pts:0, gp:2},
  'samuel rinzel_D': {pts:0, gp:2},
  'sandis vilmanis_F': {pts:0, gp:2},
  'scott laughton_F': {pts:0, gp:1},
  'sean couturier_F': {pts:1, gp:2},
  'sean durzi_D': {pts:0, gp:2},
  'sean kuraly_F': {pts:0, gp:1},
  'sean monahan_F': {pts:1, gp:1},
  'sean walker_D': {pts:0, gp:1},
  'sergei bobrovsky_G': {pts:0, gp:1},
  'seth jones_D': {pts:0, gp:2},
  'shakir mukhamadullin_D': {pts:0, gp:2},
  'shane wright_F': {pts:1, gp:1},
  'shayne gostisbehere_D': {pts:0, gp:1},
  'shea theodore_D': {pts:2, gp:1},
  'sidney crosby_F': {pts:1, gp:1},
  'simon benoit_D': {pts:0, gp:2},
  'simon holmstrom_F': {pts:0, gp:1},
  'simon nemec_D': {pts:0, gp:1},
  'spencer knight_G': {pts:0, gp:1},
  'stefan noesen_F': {pts:0, gp:1},
  'steven stamkos_F': {pts:1, gp:1},
  'tage thompson_F': {pts:0, gp:1},
  'tanner jeannot_F': {pts:0, gp:1},
  'taylor hall_F': {pts:0, gp:1},
  'teddy blueger_F': {pts:0, gp:2},
  'teuvo teravainen_F': {pts:0, gp:1},
  'thomas novak_F': {pts:1, gp:1},
  'thomas willander_D': {pts:1, gp:2},
  'timo meier_F': {pts:0, gp:1},
  'tj hughes_F': {pts:0, gp:1},
  'tom novak_F': {pts:1, gp:1},
  'tom willander_D': {pts:1, gp:2},
  'tomas hertl_F': {pts:0, gp:1},
  'tommy novak_F': {pts:1, gp:1},
  'tony deangelo_D': {pts:0, gp:1},
  'travis konecny_F': {pts:1, gp:2},
  'travis sanheim_D': {pts:2, gp:2},
  'trent frederic_F': {pts:1, gp:2},
  'trevor connelly_F': {pts:1, gp:1},
  'trevor moore_F': {pts:1, gp:1},
  'trevor van riemsdyk_D': {pts:0, gp:1},
  'trevor zegras_F': {pts:0, gp:2},
  'tristan jarry_G': {pts:0, gp:1},
  'troy stecher_D': {pts:0, gp:2},
  'tye kartye_F': {pts:0, gp:2},
  'tyler bertuzzi_F': {pts:0, gp:2},
  'tyler toffoli_F': {pts:0, gp:1},
  'tyson foerster_F': {pts:0, gp:2},
  'ukkopekka luukkonen_G': {pts:0, gp:1},
  'uvis balinskis_D': {pts:0, gp:1},
  'valeri nichushkin_F': {pts:1, gp:1},
  'vasily podkolzin_F': {pts:4, gp:2},
  'victor eklund_F': {pts:0, gp:1},
  'victor hedman_D': {pts:0, gp:1},
  'victor olofsson_F': {pts:1, gp:1},
  'ville koivunen_F': {pts:1, gp:1},
  'vince dunn_D': {pts:3, gp:1},
  'vincent trocheck_F': {pts:1, gp:1},
  'vladislav gavrikov_D': {pts:0, gp:2},
  'will borgen_D': {pts:0, gp:1},
  'will carrier_F': {pts:0, gp:1},
  'will cuylle_F': {pts:0, gp:2},
  'will karlsson_F': {pts:0, gp:1},
  'will nylander_F': {pts:2, gp:2},
  'will smith_F': {pts:3, gp:1},
  'william borgen_D': {pts:0, gp:1},
  'william carrier_F': {pts:0, gp:1},
  'william cuylle_F': {pts:0, gp:2},
  'william karlsson_F': {pts:0, gp:1},
  'william nylander_F': {pts:2, gp:2},
  'william smith_F': {pts:3, gp:1},
  'wyatt kaiser_D': {pts:1, gp:2},
  'yakov trenin_F': {pts:0, gp:1},
  'yan kuznetsov_D': {pts:0, gp:1},
  'yaroslav askarov_G': {pts:2, gp:1},
  'yegor chinakhov_F': {pts:1, gp:1},
  'yegor sharangovich_F': {pts:1, gp:1},
  'zach benson_F': {pts:1, gp:1},
  'zach bogosian_D': {pts:0, gp:1},
  'zach bolduc_F': {pts:1, gp:1},
  'zach hyman_F': {pts:0, gp:1},
  'zach metsa_D': {pts:0, gp:1},
  'zach werenski_D': {pts:2, gp:1},
  'zach whitecloud_D': {pts:0, gp:1},
  'zachary benson_F': {pts:1, gp:1},
  'zachary bogosian_D': {pts:0, gp:1},
  'zachary bolduc_F': {pts:1, gp:1},
  'zachary hyman_F': {pts:0, gp:1},
  'zachary macewen_F': {pts:0, gp:1},
  'zachary metsa_D': {pts:0, gp:1},
  'zachary ostapchuk_F': {pts:0, gp:1},
  'zachary werenski_D': {pts:2, gp:1},
  'zachary whitecloud_D': {pts:0, gp:1},
  'zack macewen_F': {pts:0, gp:1},
  'zack ostapchuk_F': {pts:0, gp:1},
  'zayne parekh_D': {pts:0, gp:1},
  'zeev buium_D': {pts:0, gp:2},
  'zemgus girgensons_F': {pts:0, gp:1},
};
